"""Subquery decorrelation: correlated scalar subqueries (COUNT, SUM, MAX and bare), EXISTS, NOT EXISTS, IN and NOT IN
with NULLs, ANY and ALL over empty and NULL sets, LATERAL and UNNEST correlation, two levels of correlation, bodies
with LIMIT, DISTINCT, GROUP BY, HAVING and windows, non-equality and OR correlation, shadowed outer names, duplicate
keys, and subqueries in the SELECT list, ON and HAVING."""

import random

from ._base import expand

CMP = "{=|<|>|<=|>=|<>}"
AGGS = "{COUNT(*)|COUNT(u.w)|SUM(u.w)|MAX(u.w)|MIN(u.w)|AVG(u.w)|COUNT(DISTINCT u.w)|ANY_VALUE(u.w)}"
CORR = "{u.k = t.y|u.k = t.x|u.w = t.x|u.k = t.y AND u.w > t.x|u.k = t.y OR u.w = t.x|u.k < t.y|u.k = t.y AND u.v = t.s|u.k IS NOT DISTINCT FROM t.y|u.k = t.y + 1}"
EXTRA = "{|AND u.w > 0|AND u.w IS NOT NULL|AND u.v = 'a'}"

TEMPLATES = [
    # scalar subqueries: the COUNT bug and empty groups
    f"SELECT t.id, (SELECT {AGGS} FROM u WHERE {CORR} {EXTRA}) AS m FROM t",
    f"SELECT t.id FROM t WHERE (SELECT {AGGS} FROM u WHERE {CORR}) {CMP} {{0|1|t.x|NULL}}",
    f"SELECT t.id FROM t WHERE {{0|t.x}} {CMP} (SELECT {AGGS} FROM u WHERE {CORR})",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM u WHERE {CORR}) {{=|<>|>|<}} (SELECT COUNT(*) FROM p WHERE p.tid = t.id)",
    f"SELECT t.id, COALESCE((SELECT {AGGS} FROM u WHERE {CORR}), {{0|-1|t.x}}) AS m FROM t",
    f"SELECT t.id, (SELECT {AGGS} FROM u WHERE {CORR}) + 1 AS m, (SELECT COUNT(*) FROM u WHERE u.k = t.y) * 2 AS c FROM t",
    f"SELECT t.id, IF((SELECT COUNT(*) FROM u WHERE u.k = t.y) = 0, 'none', 'some') AS m FROM t",
    f"SELECT t.id, (SELECT {{u.w|u.v|u.k}} FROM u WHERE {{u.k = t.y|u.k = t.id|u.w = t.x}} {{|ORDER BY u.w LIMIT 1|ORDER BY u.k DESC, u.w LIMIT 1|LIMIT 1}}) AS m FROM t",
    f"SELECT t.id, (SELECT {AGGS} FROM u WHERE {CORR} GROUP BY {{u.k|u.w|u.v}}) AS m FROM t",
    f"SELECT t.id, (SELECT {{MAX|SUM|COUNT}}(u.w) FROM u WHERE u.k = t.y HAVING {{COUNT(*) > 1|MAX(u.w) > 0|COUNT(*) = 0}}) AS m FROM t",
    f"SELECT t.id, (SELECT {{MAX|SUM|COUNT}}(w.w) FROM (SELECT u.w FROM u WHERE u.k = t.y {{|LIMIT 1|LIMIT 2}}) AS w) AS m FROM t",
    f"SELECT t.id, (SELECT MAX(u.w) FROM u WHERE u.k = t.y AND u.w < (SELECT MAX(p.n) FROM p WHERE p.tid = t.id)) AS m FROM t",
    f"SELECT t.id, (SELECT SUM(u.w) FROM u WHERE u.k = t.y AND EXISTS (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w)) AS m FROM t",
    f"SELECT t.id, (SELECT SUM((SELECT COUNT(*) FROM p WHERE p.tid = t.id AND p.id = u.w)) FROM u WHERE u.k = t.y) AS m FROM t",
    f"SELECT t.id, (SELECT {{MAX|COUNT}}(u.w) OVER () FROM u WHERE u.k = t.y {{LIMIT 1|}}) AS m FROM t",
    f"SELECT t.y, (SELECT COUNT(*) FROM u WHERE u.k = t.y) AS c FROM t GROUP BY t.y",
    f"SELECT t.y, SUM((SELECT COUNT(*) FROM u WHERE u.k = t.y)) AS c FROM t GROUP BY t.y",
    f"SELECT t.y FROM t GROUP BY t.y HAVING (SELECT COUNT(*) FROM u WHERE u.k = t.y) {{>|=}} 1",
    f"SELECT t.y, COUNT(*) AS c FROM t GROUP BY t.y HAVING COUNT(*) > (SELECT COUNT(*) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t ORDER BY (SELECT {{MAX|COUNT}}(u.w) FROM u WHERE u.k = t.y), t.id",
    f"SELECT DISTINCT t.y, (SELECT COUNT(*) FROM u WHERE u.k = t.y) AS c FROM t",
    f"SELECT t.id, (SELECT {{MAX|COUNT}}(u.w) FROM u WHERE u.k = t.id) AS m FROM t {{JOIN|LEFT JOIN}} p ON p.tid = t.id",
    f"SELECT t.id, p.id AS pid, (SELECT {{MAX|COUNT}}(u.w) FROM u WHERE u.k = p.tid) AS m FROM t {{JOIN|LEFT JOIN}} p ON p.tid = t.id",
    f"SELECT t.id, q.m FROM t LEFT JOIN (SELECT u.k, (SELECT COUNT(*) FROM p WHERE p.tid = u.k) AS m FROM u) AS q ON q.k = t.y",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y AND u.w = (SELECT {{MAX|COUNT}}(p.n) FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t JOIN u ON u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = t.id AND p.n > u.w)",
    f"SELECT t.id FROM t WHERE t.x = (SELECT MAX(t.x) FROM t WHERE t.y = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} (SELECT {{MAX|MIN|COUNT}}(t.x) FROM t AS t WHERE t.id < {{3|t.id}})",
    f"SELECT t.id, (SELECT {{MAX|COUNT}}(t2.x) FROM t AS t2 WHERE t2.y = t.y AND t2.id {{<|<>|<=}} t.id) AS m FROM t",
    f"SELECT t.id FROM t WHERE (SELECT {{MAX|COUNT}}(t2.x) FROM t AS t2 WHERE t2.y = t.y) {CMP} t.x",
    f"SELECT a.id FROM t AS a WHERE a.x = (SELECT {{MAX|MIN}}(b.x) FROM t AS b WHERE b.y = a.y AND b.id <> a.id)",
    # EXISTS and NOT EXISTS
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {CORR} {EXTRA})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT {{COUNT(*)|MAX(u.w)|u.w}} FROM u WHERE {CORR} {EXTRA})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT {{u.w|u.k}} FROM u WHERE {CORR} {{GROUP BY u.w|GROUP BY u.k HAVING COUNT(*) > 1|LIMIT 1|LIMIT 0|ORDER BY u.w LIMIT 2 OFFSET 1|OFFSET 1}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT DISTINCT u.w FROM u WHERE {CORR})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y GROUP BY u.k HAVING {{MAX(u.w) > t.x|COUNT(*) > t.x|SUM(u.w) IS NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y HAVING {{COUNT(*) > 0|COUNT(*) = 0|MAX(u.w) > 0}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT SUM(u.w) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w))",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.n > u.w AND p.tid = u.k))",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u JOIN p ON p.tid = u.k WHERE u.w = t.x AND p.id {{=|<>}} t.id)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u LEFT JOIN p ON p.tid = u.k AND p.id = t.id WHERE u.k = t.y {{|AND p.id IS NULL|AND p.id IS NOT NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y) {{AND|OR}} {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE NOT ({{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {CORR}) {{AND|OR}} t.x {{> 0|IS NULL}})",
    f"SELECT t.id, {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {CORR}) AS m FROM t",
    f"SELECT t.id, CASE WHEN EXISTS (SELECT 1 FROM u WHERE {CORR}) THEN {{1|t.x}} ELSE {{0|NULL}} END AS m FROM t",
    f"SELECT COUNT(*) AS c FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {CORR})",
    f"SELECT t.y, COUNT(*) AS c FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y) GROUP BY t.y",
    f"SELECT t.id FROM t GROUP BY t.id, t.y HAVING {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y)",
    f"SELECT DISTINCT t.y FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {CORR})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM (SELECT u.k, u.w FROM u WHERE u.w {{> 0|IS NOT NULL}}) AS d WHERE d.k = t.y)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u, UNNEST([u.w, u.k]) AS e WHERE u.k = t.y AND e = t.x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM UNNEST([t.x, t.y]) AS e WHERE e {{> 1|= 0|IS NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM UNNEST({{[1, 2]|[NULL]|[]}}) AS e WHERE e {{>|=}} t.x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y UNION {{ALL|DISTINCT}} SELECT 1 FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y {{INTERSECT|EXCEPT}} DISTINCT SELECT 1 FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = {{1|2}} AND t.x {{> 0|IS NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE {{TRUE|FALSE|NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = u.k AND {{u.w = t.x|u.w IS NULL|t.x IS NULL}})",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y) AND {{t.y IS NOT NULL|t.y > 0|t.x > 0}}",
    f"SELECT t.id FROM t JOIN u ON u.k = t.y WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u AS u2 WHERE u2.k = t.y AND u2.w {{=|<>|>}} u.w)",
    f"SELECT t.id FROM t JOIN u ON u.k = t.y WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y AND u.w {{=|<>}} 1)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t WHERE t.x {{=|>}} 1 AND t.y = t.y)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t AS t2 WHERE t2.y = t.y AND t2.id {{<|<>|=}} t.id)",
    f"SELECT t.id FROM t AS a, t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = a.y AND u.w = t.x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u AS t WHERE t.k = {{1|2}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y) AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.w = t.x)",
    # IN and NOT IN with NULLs
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE {CORR} {EXTRA})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT {{u.w|u.k|MAX(u.w)|COUNT(*)}} FROM u {{|WHERE u.w IS NOT NULL|WHERE u.k = t.y}})",
    f"SELECT t.id FROM t WHERE (t.x, t.y) {{IN|NOT IN}} (SELECT AS STRUCT u.w, u.k FROM u {{|WHERE u.k = t.y}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u {{|WHERE u.k = t.y}} {{GROUP BY u.w|GROUP BY u.w HAVING COUNT(*) > 1|LIMIT 1|ORDER BY u.w LIMIT 2}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT DISTINCT u.w FROM u {{|WHERE u.k = t.y}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y UNION {{ALL|DISTINCT}} SELECT p.n FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT p.id FROM p WHERE p.tid = t.id) {{AND|OR}} t.y {{IN|NOT IN}} (SELECT u.k FROM u)",
    f"SELECT t.id FROM t WHERE NOT (t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k {{=|<>}} t.y))",
    f"SELECT t.id FROM t WHERE (t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y)) IS {{NULL|NOT NULL|TRUE|FALSE}}",
    f"SELECT t.id FROM t WHERE (t.x {{IN|NOT IN}} (SELECT u.w FROM u {{|WHERE u.k = t.y}})) = {{TRUE|FALSE}}",
    f"SELECT t.id, t.x {{IN|NOT IN}} (SELECT u.w FROM u {{WHERE u.k = t.y|WHERE u.w IS NOT NULL|}}) AS m FROM t",
    f"SELECT t.id, CASE WHEN t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y) THEN 1 ELSE 0 END AS m FROM t",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT p.id FROM p JOIN u ON u.k = p.tid WHERE u.w = t.y)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT t2.x FROM t AS t2 WHERE t2.y = t.y AND t2.id <> t.id)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT {{u.w|t.x}} FROM u WHERE u.k = {{t.y|1}} AND {{t.x > 0|u.w > t.x}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w + t.id FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x + 1 {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE EXISTS (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.k))",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k {{IN|NOT IN}} (SELECT p.tid FROM p WHERE p.id = t.id))",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT (SELECT MAX(p.n) FROM p WHERE p.tid = u.k) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT x FROM (SELECT u.w AS x FROM u WHERE u.k = t.y) AS q)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u, UNNEST([t.y, u.k]) AS e WHERE e = u.k)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} UNNEST({{[1, 2]|[1, NULL]|[]|[t.y]}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y) {{|AND t.x IS NOT NULL|OR t.x IS NULL}}",
    f"SELECT t.y, COUNT(*) AS c FROM t GROUP BY t.y HAVING t.y {{IN|NOT IN}} (SELECT u.k FROM u WHERE u.w > COUNT(*))",
    f"SELECT t.id FROM t WHERE t.s {{IN|NOT IN}} (SELECT u.v FROM u WHERE u.k = t.y)",
    # ANY, ALL, SOME over empty and NULL sets
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL|SOME}} (SELECT u.w FROM u WHERE {CORR} {EXTRA})",
    f"SELECT t.id FROM t WHERE NOT (t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y))",
    f"SELECT t.id FROM t WHERE (t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y)) IS {{NULL|NOT NULL|TRUE|FALSE}}",
    f"SELECT t.id, t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y) AS m FROM t",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y AND u.w IS NOT NULL)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT {{MAX|MIN|SUM}}(u.w) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u {{LIMIT 1|LIMIT 0|ORDER BY u.w LIMIT 1|GROUP BY u.w|}})",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT DISTINCT u.w FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE FALSE)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT NULL FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT {{1|NULL|t.y}} UNION ALL SELECT u.w FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT p.n FROM p WHERE p.tid = t.id {{|AND p.n IS NOT NULL}})",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y) AND t.x {CMP} {{ANY|ALL}} (SELECT u.k FROM u)",
    f"SELECT t.id FROM t WHERE (t.x, t.y) {{=|<>}} {{ANY|ALL}} (SELECT AS STRUCT u.w, u.k FROM u)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT t2.x FROM t AS t2 WHERE t2.y = t.y)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT t.x FROM t WHERE t.y = 1)",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y) OR t.y IS NULL",
    f"SELECT t.id FROM t WHERE t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y AND u.w {CMP} {{ANY|ALL}} (SELECT p.n FROM p WHERE p.tid = t.id))",
    # LATERAL and UNNEST correlation
    f"SELECT t.id, l.m FROM t {{CROSS JOIN|LEFT JOIN|JOIN}} LATERAL (SELECT {{MAX|COUNT|SUM}}(u.w) AS m FROM u WHERE u.k = t.y) AS l {{|ON TRUE|ON l.m > 0}}",
    f"SELECT t.id, l.w FROM t {{CROSS JOIN|LEFT JOIN|JOIN}} LATERAL (SELECT u.w FROM u WHERE {CORR} {{|ORDER BY u.w LIMIT 1|LIMIT 1|ORDER BY u.w DESC LIMIT 2}}) AS l {{|ON TRUE|ON l.w IS NOT NULL}}",
    f"SELECT t.id, l.w FROM t, LATERAL (SELECT u.w FROM u WHERE u.k = t.y) AS l {{|WHERE l.w > 0|WHERE l.w IS NULL}}",
    f"SELECT t.id, l.m FROM t LEFT JOIN LATERAL (SELECT {{MAX|COUNT}}(u.w) AS m FROM u WHERE u.k = t.y) AS l ON TRUE WHERE l.m {{> 0|IS NULL|= 0}}",
    f"SELECT t.id, l.c FROM t CROSS JOIN LATERAL (SELECT TRUE AS c FROM u WHERE u.k = t.y GROUP BY TRUE) AS l",
    f"SELECT t.id FROM t CROSS JOIN LATERAL (SELECT 1 AS c FROM u WHERE u.k = t.y {{LIMIT 1|}}) AS l",
    f"SELECT t.id, l.c FROM t LEFT JOIN LATERAL (SELECT 1 AS c FROM u WHERE u.k = t.y {{LIMIT 1|}}) AS l ON TRUE",
    f"SELECT t.id, l.c FROM t LEFT JOIN LATERAL (SELECT DISTINCT 1 AS c FROM u WHERE u.k = t.y) AS l ON TRUE",
    f"SELECT t.id, l.c FROM t LEFT JOIN LATERAL (SELECT u.w AS c FROM u WHERE u.k = t.y) AS l ON l.c {{>|=}} t.x",
    f"SELECT t.id FROM t LEFT JOIN LATERAL (SELECT u.w AS c FROM u WHERE u.k = t.y) AS l ON TRUE WHERE l.c IS NULL",
    f"SELECT t.id FROM t CROSS JOIN LATERAL (SELECT u.w FROM u WHERE u.k = t.y) AS l WHERE l.w {{>|=}} t.x",
    f"SELECT t.id, l.w FROM t CROSS JOIN LATERAL (SELECT u.w FROM u WHERE u.k = {{1|2}}) AS l",
    f"SELECT t.id, l.n FROM t JOIN LATERAL (SELECT p.n FROM p WHERE p.tid = t.id AND p.id = (SELECT MAX(p2.id) FROM p AS p2 WHERE p2.tid = t.id)) AS l ON TRUE",
    f"SELECT t.id, l.n FROM t, LATERAL (SELECT p.n FROM p WHERE p.tid = t.id) AS l, LATERAL (SELECT u.w FROM u WHERE u.w = l.n) AS m",
    f"SELECT t.id, l.m, l2.m AS m2 FROM t LEFT JOIN LATERAL (SELECT COUNT(*) AS m FROM p WHERE p.tid = t.id) AS l ON TRUE LEFT JOIN LATERAL (SELECT COUNT(*) AS m FROM u WHERE u.w = l.m) AS l2 ON TRUE",
    f"SELECT t.id, e FROM t CROSS JOIN UNNEST({{[t.x, t.y]|[t.x, NULL]|[t.x]|[]|[t.x, t.x]}}) AS e {{|WHERE e > 0|WHERE e IS NULL}}",
    f"SELECT t.id, e FROM t LEFT JOIN UNNEST({{[t.x, t.y]|[t.x]|[]}}) AS e ON {{TRUE|e > 0|e = t.y}}",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM UNNEST([t.x, t.y]) AS e WHERE e {{>|=}} 1) {{=|>}} {{1|0|2}}",
    f"SELECT t.id FROM t WHERE (SELECT MAX(e) FROM UNNEST([t.x, t.y]) AS e) {CMP} t.id",
    f"SELECT t.id FROM t WHERE (SELECT SUM(e) FROM UNNEST({{[t.x]|[t.x, t.y]|[]}}) AS e) {CMP} {{1|0}}",
    f"SELECT t.id, ARRAY(SELECT u.w FROM u WHERE u.k = t.y) AS a FROM t",
    f"SELECT t.id FROM t WHERE ARRAY_LENGTH(ARRAY(SELECT u.w FROM u WHERE u.k = t.y)) {{>|=}} {{0|1}}",
    f"SELECT t.id, e FROM t, UNNEST(ARRAY(SELECT u.w FROM u WHERE u.k = t.y)) AS e",
    f"SELECT t.id FROM t WHERE t.x IN UNNEST(ARRAY(SELECT u.w FROM u WHERE u.k = t.y))",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM UNNEST(ARRAY(SELECT u.w FROM u WHERE u.k = t.y)) AS e WHERE e = t.x)",
    # semijoin shapes
    f"SELECT t.id FROM t JOIN u ON u.k = t.y {{|WHERE u.w > 0|WHERE u.w IS NULL}}",
    f"SELECT DISTINCT t.id FROM t JOIN u ON u.k = t.y",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT u.k FROM u) AND t.x IN (SELECT u.w FROM u)",
    f"SELECT t.id FROM t JOIN (SELECT DISTINCT u.k FROM u) AS d ON d.k = t.y",
    f"SELECT t.id FROM t JOIN (SELECT u.k FROM u GROUP BY u.k {{|HAVING COUNT(*) > 1|HAVING MAX(u.w) > 0}}) AS d ON d.k = t.y",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT u.k FROM u GROUP BY u.k {{|HAVING COUNT(*) > 1|HAVING MAX(u.w) > t.x}})",
    f"SELECT t.id, t.x FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y) {{UNION ALL|UNION DISTINCT|EXCEPT DISTINCT|INTERSECT DISTINCT}} SELECT t.id, t.x FROM t WHERE t.x > 0",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y WHERE u.k {{IS NULL|IS NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y AND u.w > 0 WHERE u.k {{IS NULL|IS NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y AND u.w > t.x WHERE u.w IS NULL",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y WHERE u.w IS NULL",
    f"SELECT t.id FROM t WHERE t.y {{IN|NOT IN}} (SELECT u.k FROM u) AND t.y {{IN|NOT IN}} (SELECT u.k FROM u WHERE u.w > 0)",
    f"SELECT t.id, p.id FROM t JOIN p ON p.tid = t.id WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p AS p2 WHERE p2.tid = t.id AND p2.id {{<|<>|>}} p.id)",
    f"SELECT p.id FROM p WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t WHERE t.id = p.tid {{|AND t.x > 0|AND t.x IS NULL}})",
    f"SELECT p.id FROM p WHERE p.tid {{IN|NOT IN}} (SELECT t.id FROM t {{|WHERE t.x > 0}})",
    f"SELECT p.id FROM p WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t JOIN u ON u.k = t.y WHERE t.id = p.tid AND u.w = p.id)",
    # self-witnessed and domain joins
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS t2 WHERE t2.id = t.id {{|AND t2.x > 0|AND t2.x IS NOT NULL}})",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t AS t2 WHERE t2.x = t.x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t AS t2 WHERE t2.x IS NOT DISTINCT FROM t.x AND t2.id <> t.id)",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT t2.x FROM t AS t2 WHERE t2.id = t.id)",
    f"SELECT t.id FROM t WHERE t.x NOT IN (SELECT t2.x FROM t AS t2 WHERE t2.id = t.id)",
    f"SELECT t.id FROM t WHERE t.x {CMP} ALL (SELECT t2.x FROM t AS t2 WHERE t2.id = t.id)",
    f"SELECT t.id FROM t WHERE t.x {CMP} ANY (SELECT t2.x FROM t AS t2 WHERE t2.id = t.id)",
    f"SELECT t.id, (SELECT t2.x FROM t AS t2 WHERE t2.id = t.id) AS m FROM t",
    f"SELECT t.id, (SELECT COUNT(*) FROM t AS t2 WHERE t2.id = t.id) AS m FROM t",
    f"SELECT t.id, (SELECT COUNT(*) FROM t AS t2 WHERE t2.x = t.x) AS m FROM t",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM t AS t2 WHERE t2.y = t.y) {{=|>|<}} {{1|2}}",
    f"SELECT t.y FROM t GROUP BY t.y HAVING COUNT(*) {{=|>}} (SELECT COUNT(*) FROM t AS t2 WHERE t2.y = t.y)",
    f"SELECT t.id FROM t JOIN (SELECT DISTINCT t3.y FROM t AS t3) AS d ON d.y = t.y WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = d.y)",
    # correlated derived tables
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM (SELECT u.w AS a, u.k AS b FROM u WHERE u.k = t.y) AS d WHERE d.a {{> 0|= 0|IS NULL}})",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT d.a FROM (SELECT u.w AS a FROM u WHERE u.k = t.y) AS d)",
    f"SELECT t.id, (SELECT {{MAX|COUNT}}(d.a) FROM (SELECT u.w AS a FROM u WHERE u.k = t.y) AS d) AS m FROM t",
    f"SELECT t.id, (SELECT {{MAX|COUNT}}(d.a) FROM (SELECT u.w + t.x AS a FROM u WHERE u.k = t.y) AS d) AS m FROM t",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM (SELECT u.w AS a FROM u) AS d JOIN p ON p.n = d.a WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT u.w AS a FROM u WHERE u.k = t.y) AS d, (SELECT p.n AS b FROM p WHERE p.tid = t.id) AS e WHERE d.a = e.b)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT u.w AS t FROM u WHERE u.k = t.y) AS d WHERE d.t > 0)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT u.w AS a, u.w AS a FROM u WHERE u.k = t.y) AS d)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM (SELECT u.w AS a FROM u WHERE u.k = t.y {{LIMIT 1|}}) AS d LEFT JOIN p ON p.n = d.a AND p.tid = t.id WHERE p.id IS NULL)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM p LEFT JOIN (SELECT u.w AS a FROM u WHERE u.k = t.y) AS d ON p.n = d.a WHERE p.tid = t.id AND d.a IS NULL)",
    # correlated predicates in various places
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y) = {{TRUE|FALSE}}",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM u WHERE u.k = t.y) {{>|>=|=|<>}} {{0|1}} {{AND|OR}} t.x {{> 0|IS NULL}}",
    f"SELECT t.id FROM t WHERE COALESCE((SELECT MAX(u.w) FROM u WHERE u.k = t.y), -1) {CMP} t.x",
    f"SELECT t.id FROM t WHERE (SELECT MAX(u.w) FROM u WHERE u.k = t.y) IS {{NULL|NOT NULL}}",
    f"SELECT t.id FROM t WHERE (SELECT SUM(u.w) FROM u WHERE u.k = t.y) IS {{NULL|NOT NULL}}",
    f"SELECT t.id FROM t WHERE (SELECT MAX(u.w) FROM u WHERE u.k = t.y) IS DISTINCT FROM t.x",
    f"SELECT t.id FROM t WHERE (SELECT MAX(u.w) FROM u WHERE u.k = t.y) = (SELECT MAX(p.n) FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE t.x = (SELECT {{MAX|MIN}}(u.w) FROM u WHERE u.k = t.y) OR t.x IS NULL",
    f"SELECT t.id FROM t WHERE NOT (t.x = (SELECT {{MAX|MIN|COUNT}}(u.w) FROM u WHERE u.k = t.y))",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM u WHERE u.k = t.y AND u.w {CMP} t.x) {{=|>|<}} (SELECT COUNT(*) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(*) FROM u WHERE u.k = t.y) = (SELECT COUNT(*) FROM u WHERE u.k = t.y AND u.w IS NOT NULL)",
    f"SELECT t.id FROM t WHERE (SELECT COUNT(DISTINCT u.w) FROM u WHERE u.k = t.y) {{=|>}} (SELECT COUNT(u.w) FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t WHERE (SELECT {{MAX|SUM|COUNT}}(u.w) FROM u WHERE u.k = {{t.y|t.id}}) {CMP} (SELECT {{MAX|SUM|COUNT}}(u.w) FROM u WHERE u.k = {{t.y|t.x}})",
    f"SELECT t.id FROM t WHERE t.y = (SELECT u.k FROM u WHERE u.w = t.x AND u.k = (SELECT MAX(p.tid) FROM p WHERE p.n = u.w))",
    f"SELECT t.id FROM t, u WHERE u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = t.id AND p.n = u.w)",
    f"SELECT t.id FROM t, u WHERE u.k = t.y AND (SELECT COUNT(*) FROM p WHERE p.tid = t.id AND p.n = u.w) {{=|>}} 1",
    f"SELECT t.id FROM t JOIN u ON u.k = t.y AND u.w = (SELECT COUNT(*) FROM p WHERE p.tid = t.id)",
    f"SELECT t.id FROM t WHERE t.id IN (SELECT p.tid FROM p WHERE (SELECT COUNT(*) FROM u WHERE u.k = p.tid) {{=|>}} t.x)",
    f"SELECT t.id FROM t WHERE t.id IN (SELECT p.tid FROM p WHERE p.n = (SELECT MAX(u.w) FROM u WHERE u.k = t.y))",
    f"SELECT t.id FROM t WHERE t.id {{IN|NOT IN}} (SELECT p.tid FROM p WHERE p.id IN (SELECT u.w FROM u WHERE u.k = t.y))",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y AND EXISTS (SELECT 1 FROM p WHERE p.tid = u.k AND p.id = t.id))",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE EXISTS (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w))",
    f"SELECT t.id FROM t WHERE NOT EXISTS (SELECT 1 FROM u WHERE NOT EXISTS (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w))",
    f"SELECT t.id FROM t WHERE NOT EXISTS (SELECT 1 FROM u WHERE u.k = t.y AND NOT EXISTS (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w))",
    f"SELECT t.id FROM t WHERE t.x {CMP} (SELECT u.w FROM u WHERE u.k = t.y AND u.w = (SELECT MIN(u2.w) FROM u AS u2 WHERE u2.k = u.k))",
    # shadowing
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u AS t WHERE t.k = {{1|2}} AND t.w > 0)",
    f"SELECT t.id FROM t WHERE (SELECT {{MAX|COUNT}}(t.w) FROM u AS t WHERE t.k = 1) {CMP} t.x",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y AND EXISTS (SELECT 1 FROM p AS u WHERE u.tid = t.id AND u.id > 0))",
    f"SELECT u.k FROM u WHERE EXISTS (SELECT 1 FROM t AS u WHERE u.id = 1) AND u.w {{> 0|IS NULL}}",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u AS t2 WHERE t2.k = x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = x)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE w = t.x)",
    f"SELECT t.id FROM t WHERE (SELECT {{MAX|COUNT}}(w) FROM u WHERE k = t.y) {CMP} x",
    f"WITH u AS (SELECT p.tid AS k, p.id AS w FROM p) SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = t.y)",
    f"WITH c AS (SELECT u.k, MAX(u.w) AS m, COUNT(*) AS n FROM u GROUP BY u.k) SELECT t.id, (SELECT c.n FROM c WHERE c.k = t.y) AS n FROM t",
    f"WITH c AS (SELECT u.k, MAX(u.w) AS m FROM u GROUP BY u.k) SELECT t.id FROM t WHERE t.x {CMP} (SELECT c.m FROM c WHERE c.k = t.y)",
    f"WITH c AS (SELECT u.k, COUNT(*) AS n FROM u GROUP BY u.k) SELECT t.id, COALESCE((SELECT c.n FROM c WHERE c.k = t.y), 0) AS n FROM t",
    f"WITH c AS (SELECT DISTINCT u.k FROM u) SELECT t.id FROM t WHERE t.y {{IN|NOT IN}} (SELECT c.k FROM c)",
    # windows and ordering inside
    f"SELECT t.id, (SELECT {{ROW_NUMBER|RANK|COUNT}}() OVER (ORDER BY u.w) FROM u WHERE u.k = t.y {{ORDER BY u.w LIMIT 1|LIMIT 1|}}) AS m FROM t",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT u.w, ROW_NUMBER() OVER (ORDER BY u.w) AS rn FROM u WHERE u.k = t.y) AS d WHERE d.rn {{=|>}} 2)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT d.w FROM (SELECT u.w, ROW_NUMBER() OVER (PARTITION BY u.k ORDER BY u.w) AS rn FROM u) AS d WHERE d.rn = 1 AND d.w {{>|=}} t.y)",
    f"SELECT t.id FROM t WHERE t.x = (SELECT u.w FROM u WHERE u.k = t.y QUALIFY ROW_NUMBER() OVER (ORDER BY u.w DESC) = 1)",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.y QUALIFY ROW_NUMBER() OVER (ORDER BY u.w) = 1)",
    f"SELECT t.id, SUM((SELECT COUNT(*) FROM u WHERE u.k = t.y)) OVER (PARTITION BY t.y) AS m FROM t",
    f"SELECT t.id, (SELECT COUNT(*) FROM u WHERE u.k = t.y) AS c, ROW_NUMBER() OVER (ORDER BY (SELECT COUNT(*) FROM u WHERE u.k = t.y), t.id) AS r FROM t",
    f"SELECT t.id, (SELECT MAX(u.w) FROM u WHERE u.k = t.y) AS c FROM t ORDER BY c, t.id LIMIT 2",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y) ORDER BY t.id LIMIT 2",
    # constant and uncorrelated subqueries
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = {{1|2}}) {{AND|OR}} t.x {{> 0|IS NULL}}",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u {{WHERE u.w > 0|WHERE FALSE|LIMIT 0|}})",
    f"SELECT t.id FROM t WHERE (SELECT {{COUNT(*)|MAX(u.w)|SUM(u.w)}} FROM u WHERE u.k = {{1|2}}) {CMP} t.x",
    f"SELECT t.id FROM t WHERE t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = {{1|2}})",
    f"SELECT t.id FROM t WHERE t.x = (SELECT u.w FROM u WHERE u.k = {{1|2}})",
    f"SELECT t.id FROM t WHERE t.x = (SELECT u.w FROM u WHERE u.k = {{1|2}} LIMIT 1)",
    f"SELECT t.id FROM t CROSS JOIN (SELECT {{MAX|COUNT}}(u.w) AS m FROM u WHERE u.k = 1) AS q WHERE t.x {CMP} q.m",
    f"SELECT t.id FROM t CROSS JOIN (SELECT 1 AS c FROM u WHERE u.k = {{1|2}} GROUP BY TRUE) AS q",
    f"SELECT t.id FROM t JOIN (SELECT TRUE AS c FROM u WHERE u.w {{> 0|IS NULL}} GROUP BY TRUE) AS q ON TRUE",
    f"SELECT t.id FROM t WHERE t.x > 0 AND t.x = 1 AND EXISTS (SELECT 1 FROM u WHERE u.k = t.x AND u.w = t.y)",
    f"SELECT t.id FROM t WHERE t.x = t.y AND EXISTS (SELECT 1 FROM u WHERE u.k = t.x) AND NOT EXISTS (SELECT 1 FROM p WHERE p.tid = t.y)",
    f"SELECT t.id FROM t WHERE t.x IS NULL AND EXISTS (SELECT 1 FROM u WHERE u.k = t.x)",
    f"SELECT t.id FROM t WHERE t.x IS NOT DISTINCT FROM t.y AND EXISTS (SELECT 1 FROM u WHERE u.k = t.x)",
    f"SELECT t.id FROM t WHERE t.x = 1 AND (SELECT COUNT(*) FROM u WHERE u.k = t.x) {CMP} t.y",
    f"SELECT t.id FROM t WHERE t.x = 1 AND t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k = t.x)",
    f"SELECT t.id FROM t WHERE t.x = t.y AND t.x {CMP} {{ANY|ALL}} (SELECT u.w FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t JOIN u ON u.k = t.y AND t.x = 1 WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = u.k AND p.id = t.x)",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y WHERE t.y = 1 AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = u.k)",
    f"SELECT t.id FROM t LEFT JOIN u ON u.k = t.y WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = u.k AND p.id = u.w)",
    f"SELECT t.id, u.w FROM t LEFT JOIN u ON u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.tid = t.id AND p.id = u.w)",
    f"SELECT t.id, u.w FROM t RIGHT JOIN u ON u.k = t.y AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM p WHERE p.id = u.w)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = p.tid AND u.w = p.id)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE p.id IS NULL AND {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = p.tid)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = p.tid) OR p.id IS NULL",
    f"SELECT t.id, EXISTS (SELECT 1 FROM p WHERE p.tid = t.id) AS m FROM t LEFT JOIN p ON p.tid = t.id",
    # Calcite-style lateral indicator groups, FK-witnessed EXISTS, select-list membership on NOT NULL columns
    f"SELECT t.id, l.c FROM t LEFT JOIN LATERAL (SELECT u.k IS NOT NULL AS c FROM u WHERE {{u.k = t.y|u.k > t.y|u.k = t.y AND u.w > 0|u.w = t.x|u.w = t.x AND u.k IS NOT NULL}} GROUP BY u.k IS NOT NULL) AS l ON TRUE",
    f"SELECT t.id, l.c IS NULL AS m FROM t LEFT JOIN LATERAL (SELECT u.k IS NOT NULL AS c FROM u WHERE u.k = t.y GROUP BY u.k IS NOT NULL) AS l ON TRUE",
    f"SELECT t.id FROM t LEFT JOIN LATERAL (SELECT u.k IS NOT NULL AS c FROM u WHERE u.k = t.y GROUP BY u.k IS NOT NULL) AS l ON TRUE WHERE {{l.c|l.c IS NULL|COALESCE(l.c, FALSE)|NOT l.c}}",
    f"SELECT t.y, COUNT(l.c) AS n, COUNT(*) AS m FROM t LEFT JOIN LATERAL (SELECT u.k IS NOT NULL AS c FROM u WHERE u.k = t.y GROUP BY u.k IS NOT NULL) AS l ON TRUE GROUP BY t.y",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u {{|WHERE u.k = u.k|WHERE u.k IS NOT NULL|WHERE u.w IS NOT NULL|WHERE u.k = u.k AND u.w = u.w}})",
    f"SELECT p.id FROM p WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM t {{|WHERE t.id = t.id|WHERE t.id IS NOT NULL|WHERE t.x IS NOT NULL|WHERE t.x = t.x}})",
    f"SELECT p.id FROM p JOIN t ON t.id = p.tid WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u {{|WHERE u.k = u.k}})",
    f"SELECT p.id FROM p LEFT JOIN t ON t.id = p.tid WHERE EXISTS (SELECT 1 FROM t AS t2 {{|WHERE t2.id IS NOT NULL}})",
    f"SELECT t.id FROM (SELECT * FROM t WHERE t.y = {{1|2}}) AS d JOIN t ON t.id = d.id WHERE EXISTS (SELECT 1 FROM u WHERE u.k = d.y)",
    f"SELECT d.id FROM (SELECT t.id, t.y FROM t WHERE t.y = {{1|2}}) AS d WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = d.y AND u.w {{>|=}} d.y)",
    f"SELECT d.id FROM (SELECT t.id, t.y FROM t WHERE t.y = 1) AS d LEFT JOIN p ON p.tid = d.id WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM u WHERE u.k = d.y)",
    f"SELECT t.id, t.x IN (SELECT u.w FROM u {{|WHERE u.k = 1}}) AS m FROM t",
    f"SELECT t.id, t.x {{IN|NOT IN}} (SELECT u.w FROM u WHERE u.k > t.y) AS m, t.y IN (SELECT u.k FROM u) AS n FROM t",
    f"SELECT d.id, d.x IN (SELECT u.w FROM u) AS m FROM (SELECT t.id, t.x AS x FROM t) AS d",
    f"SELECT t.id FROM t WHERE t.x {{>|<|>=|<=}} ANY (SELECT u.w FROM u {{|WHERE u.k = t.y|WHERE u.k > 0}})",
    f"SELECT t.id, CASE WHEN t.x {{>|<}} ANY (SELECT u.w FROM u WHERE u.k = t.y) THEN 1 ELSE 0 END AS m FROM t",
    f"SELECT d.id FROM (SELECT t.id, t.x FROM t) AS d WHERE d.x {{>|<}} ANY (SELECT u.w FROM u WHERE u.k > d.id)",
    f"SELECT t.id, t.x {{>|<}} ANY (SELECT u.w FROM u WHERE u.k = t.y) AS m FROM t",
    f"SELECT t.id FROM t WHERE (t.x > ANY (SELECT u.w FROM u WHERE u.k = t.y)) IS NULL",
    f"SELECT t.id FROM t WHERE COALESCE(t.x > ANY (SELECT u.w FROM u WHERE u.k = t.y), {{TRUE|FALSE}})",
    f"SELECT t.id FROM t WHERE t.x IS NOT NULL AND t.x {{>|<}} ALL (SELECT u.w FROM u WHERE u.k = t.y)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id AND EXISTS (SELECT 1 FROM u WHERE u.k = {{1|2}})",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id AND {{NOT EXISTS|EXISTS}} (SELECT 1 FROM u WHERE u.w > 0)",
    f"SELECT t.id, p.id AS pid FROM t LEFT JOIN p ON p.tid = t.id AND NOT EXISTS (SELECT 1 FROM u) WHERE p.id IS NULL",
    f"SELECT DISTINCT t.id FROM t JOIN u ON u.k = t.y",
    f"SELECT DISTINCT t.y FROM t JOIN u ON u.k = t.y {{|WHERE u.w > 0|WHERE u.w IS NULL}}",
    f"SELECT t.y, MAX(t.x) AS m FROM t JOIN u ON u.k = t.y GROUP BY t.y",
    f"SELECT t.y, COUNT(DISTINCT t.x) AS m FROM t JOIN u ON u.k = t.y JOIN p ON p.tid = t.id GROUP BY t.y",
    f"SELECT t.y FROM t JOIN u ON u.k = t.y GROUP BY t.y HAVING {{MAX(t.x) > 1|COUNT(*) > 1|MIN(t.x) IS NULL}}",
    f"SELECT DISTINCT t.y FROM t, u WHERE u.k = t.y AND u.w > t.x",
    f"SELECT DISTINCT t.y FROM t LEFT JOIN p ON p.tid = t.id JOIN u ON u.k = p.tid",
    f"SELECT DISTINCT t.y FROM t JOIN (SELECT u.k FROM u WHERE u.w > 0) AS d ON d.k = t.y",
    f"SELECT DISTINCT t.y FROM t JOIN (SELECT u.k, COUNT(*) AS c FROM u GROUP BY u.k) AS d ON d.k = t.y {{|WHERE d.c > 1|WHERE d.c IS NULL}}",
    f"SELECT t.id, g.c FROM t {{LEFT JOIN|JOIN}} (SELECT u.k, COUNT(*) AS c, MAX(u.w) AS m FROM u GROUP BY u.k) AS g ON g.k = t.y",
    f"SELECT t.id, g.c, g.m FROM t {{LEFT JOIN|JOIN}} (SELECT d.a AS k, COUNT(u.w) AS c, MAX(u.w) AS m FROM (SELECT DISTINCT t3.y AS a FROM t AS t3) AS d LEFT JOIN u ON d.a IS NOT DISTINCT FROM u.k GROUP BY d.a) AS g ON g.k = t.y",
    f"SELECT t.id, g.c FROM t JOIN (SELECT d.a AS k, COUNT(u.w) AS c FROM (SELECT t3.y AS a FROM t AS t3 GROUP BY t3.y) AS d LEFT JOIN (SELECT u.k, COUNT(*) AS c FROM u GROUP BY u.k) AS u ON u.k = d.a GROUP BY d.a) AS g ON g.k = t.y",
    f"SELECT t.id, g.k FROM t JOIN (SELECT t3.y AS k FROM t AS t3 GROUP BY t3.y) AS g ON g.k = t.y",
    f"SELECT t.id, g.k FROM t JOIN (SELECT DISTINCT t3.x AS k FROM t AS t3) AS g ON g.k = t.x",
    f"SELECT t.id, g.k FROM t JOIN (SELECT t3.x AS k FROM t AS t3 GROUP BY t3.x) AS g ON g.k IS NOT DISTINCT FROM t.x",
    f"SELECT t.id, g.k FROM t LEFT JOIN (SELECT t3.x AS k FROM t AS t3 GROUP BY t3.x) AS g ON g.k = t.x",
    f"SELECT t.id FROM t AS a, t WHERE EXISTS (SELECT 1 FROM t AS t4 WHERE t4.id = a.id) AND t.id = a.id",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE EXISTS (SELECT 1 FROM t AS t2 WHERE t2.id = p.tid)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS t2 WHERE t2.id = t.id AND t2.x = t.x)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS t2 WHERE t2.x IS NOT DISTINCT FROM t.x AND t2.y IS NOT DISTINCT FROM t.y)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS t2 WHERE t2.y = t.y)",
    f"SELECT t.id FROM t WHERE NOT EXISTS (SELECT 1 FROM t AS t2 WHERE t2.id = t.id)",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u) AND t.x IN (SELECT u.w FROM u WHERE u.k > 0)",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE u.w > 0 AND u.w IN (SELECT p.id FROM p))",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE u.w {{>|IS NULL OR u.w >|=}} 0 AND u.k = 1)",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE {{NOT|}} u.w IN (SELECT p.tid FROM p)) {{|OR t.y = 1}}",
    f"SELECT t.id FROM t WHERE t.x NOT IN (SELECT u.w FROM u WHERE u.w IN (1, NULL))",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE u.w NOT IN (SELECT p.tid FROM p))",
    f"SELECT t.id FROM t WHERE (t.x + 1) IN (SELECT u.w FROM u WHERE u.w {{>|<}} 3 AND u.w IN (SELECT p.tid FROM p))",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE u.w IS NULL OR u.w IN (SELECT p.tid FROM p))",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE CAST(u.w AS STRING) = '1' AND u.w IN (1))",
    f"SELECT t.id FROM t WHERE t.f IN (SELECT u.w FROM u WHERE u.w > 0 AND u.w IN (SELECT p.tid FROM p))",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT u.w FROM u WHERE u.w IN (SELECT p.tid FROM p WHERE p.id = u.k))",
    # the outer value and the subquery column of different numeric types (a double past 2**53 meets several integers)
    f"SELECT t.id FROM t WHERE {{t.f|t.x}} IN (SELECT u.w FROM u WHERE u.w {{=|>|<>|<=}} {{9007199254740993|9007199254740992|1}} {{|AND u.w IN (SELECT p.id FROM p)}})",
    f"SELECT t.id FROM t WHERE t.f IN (SELECT u.w FROM u WHERE u.w IN (SELECT p.tid FROM p) AND u.w {{=|<>}} {{9007199254740993|2}})",
    f"SELECT p.id FROM p WHERE p.n IN (SELECT u.w FROM u WHERE u.w {{=|>|<>}} {{9007199254740993|1|2}} {{|AND u.w IN (SELECT t.x FROM t)}})",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT p.n FROM p WHERE p.n {{=|>}} {{9007199254740993|2}} AND p.n IN (SELECT u.w FROM u))",
]


_NULLABLE = {"t": ["x", "y"], "u": ["w", "v"], "p": ["tid", "n", "b"]}


def cases(seed: int, count: int) -> list[dict]:
    """Template cases, a third of them with extra NOT NULL columns (the rules that read declared nullability)."""

    rng = random.Random(seed * 31 + 7)
    out = expand(TEMPLATES, seed, count, "decorrelation")
    for case in out:
        if rng.random() < 0.35:
            constraints = case["constraints"]
            for table, columns in _NULLABLE.items():
                for column in columns:
                    if rng.random() < 0.5:
                        rules = constraints.setdefault(table, {"not_null": [], "keys": []})
                        if column not in rules.setdefault("not_null", []):
                            rules["not_null"].append(column)
            if rng.random() < 0.5:
                constraints.setdefault("u", {"not_null": [], "keys": []})
                constraints["u"].setdefault("keys", [["k"]])
                constraints["u"].setdefault("not_null", [])
                if "k" not in constraints["u"]["not_null"]:
                    constraints["u"]["not_null"].append("k")
    return out
