"""Derived-table, CTE, projection and star rewrites: flattening a joined derived table, unwrapping and inlining
projections, pruning unread columns, lifting a derived ORDER BY .. LIMIT, pushing filters inside, SELECT * peeling
and expansion (with EXCEPT / REPLACE), CTE inlining (including CTEs that shadow tables) and union-source canonicalization.

Each family lists the shape a rule fires on and near misses a guard must decline: duplicate output names, a derived
table's ORDER BY / LIMIT that must stay, a filter above an aggregate or a LIMIT, shadowed aliases, columns the
outer query reads from another source."""

from ._base import expand

JOIN = "{LEFT JOIN|JOIN|FULL JOIN|RIGHT JOIN}"
AGG = "{COUNT(*)|COUNT(d.n)|SUM(d.n)|MIN(d.n)|MAX(d.n)}"
ORDER = "{x, id|id|x DESC, id|y, x, id}"

TEMPLATES = [
    # _flatten_join_source: a grouped / aggregate select over a derived table that only projects a join's columns
    f"SELECT d.y, {AGG} AS c FROM (SELECT t.y, p.n FROM t {JOIN} p ON p.tid = t.id) AS d GROUP BY d.y",
    f"SELECT {AGG} AS c FROM (SELECT t.id, p.n FROM t {JOIN} p ON p.tid = t.id) AS d",
    f"SELECT d.id, {AGG} AS c FROM (SELECT t.id, p.n, p.b FROM t {JOIN} p ON p.tid = t.id AND {{p.b|p.n > 0|t.x > 0}}) AS d GROUP BY d.id",
    f"SELECT COUNT(*) AS c FROM (SELECT t.id, p.id FROM t {JOIN} p ON p.tid = t.id) AS d",
    f"SELECT d.k, COUNT(*) AS c FROM (SELECT t.y, u.k FROM t {JOIN} u ON u.k = t.y) AS d GROUP BY d.k",
    f"SELECT d.y, COUNT(DISTINCT d.n) AS c FROM (SELECT t.y, p.n FROM t LEFT JOIN p ON p.tid = t.id WHERE {{t.x > 0|p.n IS NULL}}) AS d GROUP BY d.y",
    f"SELECT COUNT(*) AS c FROM (SELECT t.id FROM t JOIN p ON p.tid = t.id JOIN u ON u.k = t.y) AS d",
    # lift_derived_expressions: computed columns of a derived outer join move into the grouped select above
    f"SELECT d.z, COUNT(*) AS c FROM (SELECT t.x + 1 AS z, p.id AS pid FROM t LEFT JOIN p ON p.tid = t.id) AS d GROUP BY d.z",
    f"SELECT d.z, {{COUNT(d.pid)|SUM(d.pid)|MAX(d.z)}} AS c FROM (SELECT {{t.x * 2|COALESCE(t.x, 0)|t.x + t.y|CASE WHEN t.x > 0 THEN 1 ELSE 0 END}} AS z, p.id AS pid FROM t {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} p ON p.tid = t.id) AS d GROUP BY d.z",
    f"SELECT {{d.z|d.z + 1}} AS z, COUNT(*) AS c FROM (SELECT t.x - 1 AS z, t.y AS y, p.n AS n FROM t LEFT JOIN p ON p.tid = t.id) AS d GROUP BY {{d.z|d.z + 1}}",
    # _unwrap_projection: a select that only lists columns of a grouped / aggregate derived table
    f"SELECT d.a, d.b FROM (SELECT t.y AS a, SUM(t.x) AS b, COUNT(*) AS c FROM t GROUP BY t.y) AS d",
    f"SELECT d.b AS q, d.b AS r FROM (SELECT t.y AS a, {{SUM(t.x)|MAX(t.x)|COUNT(t.x)}} AS b FROM t GROUP BY t.y) AS d",
    f"SELECT d.a FROM (SELECT {{SUM(t.x)|COUNT(*)|MAX(t.x)}} AS a, COUNT(t.y) AS b FROM t {{|WHERE t.x > 100}}) AS d",
    f"SELECT d.k FROM (SELECT t.y AS k, COUNT(*) AS c FROM t GROUP BY t.y {{|HAVING COUNT(*) > 1}}) AS d",
    f"SELECT d.c FROM (SELECT t.y AS k, COUNT(*) AS c FROM t GROUP BY t.y ORDER BY c {{|LIMIT 2}}) AS d",
    f"SELECT d.a, d.a AS again FROM (SELECT t.y AS a, t.y AS b FROM t GROUP BY t.y) AS d",
    f"SELECT 1 AS one FROM (SELECT {{SUM(t.x)|COUNT(*)}} AS a FROM t) AS d",
    f"SELECT d.k FROM (SELECT t.y AS k, SUM(t.x) AS s FROM t GROUP BY t.y) AS d WHERE d.s > 1",
    # _unwrap_distinct_projection: every output of a DISTINCT derived table listed once
    f"SELECT d.a, d.b FROM (SELECT DISTINCT t.x AS a, t.y AS b FROM t) AS d",
    f"SELECT d.b AS q, d.a AS r FROM (SELECT DISTINCT t.x AS a, t.y AS b FROM t {{|WHERE t.x > 0}}) AS d",
    f"SELECT d.a FROM (SELECT DISTINCT t.x AS a, t.y AS b FROM t) AS d",
    f"SELECT d.a, d.a AS a2 FROM (SELECT DISTINCT t.x AS a, t.y AS b FROM t) AS d",
    f"SELECT d.a, d.b FROM (SELECT DISTINCT t.x AS a, t.x AS b FROM t) AS d",
    f"SELECT d.a, d.b FROM (SELECT DISTINCT t.x AS a, t.y AS b FROM t ORDER BY t.x LIMIT 2) AS d",
    # _push_filter_into_derived: a condition on kept values moves inside; one on aggregates or under LIMIT must not
    f"SELECT d.k FROM (SELECT DISTINCT t.y AS k FROM t) AS d WHERE {{d.k > 1|d.k IS NULL|d.k = 1 OR d.k IS NULL|d.k > 1 AND d.k < 3}}",
    f"SELECT d.k, d.c FROM (SELECT t.y AS k, COUNT(*) AS c FROM t GROUP BY t.y) AS d WHERE {{d.k > 1|d.c > 1|d.k > 1 AND d.c > 1|d.k = d.c}}",
    f"SELECT d.k FROM (SELECT t.y AS k, t.x AS j FROM t GROUP BY t.y, t.x) AS d WHERE {{d.k > 1|d.j > 1|d.k > d.j}}",
    f"SELECT d.k FROM (SELECT DISTINCT t.y AS k FROM t ORDER BY k LIMIT 2) AS d WHERE d.k > 1",
    f"SELECT d.k FROM (SELECT t.y AS k FROM t GROUP BY t.y ORDER BY t.y LIMIT 2 OFFSET 1) AS d WHERE d.k > 1",
    f"SELECT d.k FROM (SELECT DISTINCT t.y + 1 AS k FROM t) AS d WHERE d.k > 1 AND EXISTS (SELECT 1 FROM u WHERE u.k = d.k)",
    # _lift_limit_derived / limit_rule: a derived ORDER BY .. LIMIT is lifted or kept, never lost or moved
    f"SELECT d.id FROM (SELECT id, x FROM t ORDER BY {ORDER} LIMIT {{1|3}}) AS d",
    f"SELECT d.id, d.x AS q FROM (SELECT id, x FROM t ORDER BY id LIMIT 3 {{|OFFSET 1}}) AS d",
    f"SELECT d.id FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d WHERE d.x {{> 0|IS NULL}}",
    f"SELECT d.id FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d ORDER BY d.x, d.id",
    f"SELECT DISTINCT d.x FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT COUNT(*) AS c FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT d.id, u.v FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d JOIN u ON u.k = d.x",
    f"SELECT d.id FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d LIMIT {{2|5}}",
    f"SELECT d.id FROM (SELECT d.id, d.x FROM (SELECT id, x FROM t ORDER BY id LIMIT 4) AS d ORDER BY d.x, d.id LIMIT 2) AS d",
    f"SELECT d.id FROM (SELECT id, x + 1 AS id2, id AS id3 FROM t ORDER BY id2, id LIMIT 3) AS d",
    f"SELECT d.n FROM (SELECT id AS n, x AS id FROM t ORDER BY id, n LIMIT 3) AS d",
    f"SELECT d.id AS q FROM (SELECT id, x AS q FROM t ORDER BY q, id LIMIT 3) AS d",
    f"SELECT d.s FROM (SELECT SUM(x) AS s, y FROM t GROUP BY y ORDER BY s, y LIMIT 2) AS d",
    f"SELECT d.s FROM (SELECT SUM(x) AS s, COUNT(*) AS c FROM t ORDER BY s LIMIT 2) AS d",
    # _peel_star_wrappers / _expand_stars: SELECT * through wrappers, with EXCEPT and REPLACE
    f"SELECT * FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT * FROM (SELECT x, y FROM t ORDER BY x, y, id LIMIT 3) AS d",
    f"SELECT d.* FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT * EXCEPT (x) FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT * REPLACE (id + 1 AS id) FROM (SELECT id, x FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT * FROM (SELECT * FROM (SELECT id, x FROM t WHERE x > 0) AS a) AS b",
    f"SELECT * FROM {{t|u|p}}",
    f"SELECT * EXCEPT ({{x|x, y|id}}) FROM t",
    f"SELECT * REPLACE ({{x + 1 AS x|COALESCE(x, 0) AS x|id * 2 AS id, x + 1 AS x}}) FROM t",
    f"SELECT * EXCEPT (y) REPLACE (x + 1 AS x) FROM t",
    f"SELECT t.* EXCEPT (x), u.v FROM t JOIN u ON u.k = t.y",
    f"SELECT t.*, u.* FROM t {JOIN} u ON u.k = t.y",
    f"SELECT * FROM t {JOIN} u ON u.k = t.y",
    f"SELECT * FROM (SELECT * FROM t) AS a {JOIN} (SELECT * FROM u) AS b ON b.k = a.y",
    f"SELECT d.* FROM (SELECT * FROM t WHERE x > 0) AS d WHERE d.y > 0",
    f"SELECT COUNT(*) AS c FROM (SELECT * FROM t) AS d WHERE d.x > 0",
    f"SELECT * FROM (SELECT x, x FROM t) AS d",
    f"SELECT * FROM (SELECT x AS a, y AS a FROM t) AS d",
    f"SELECT * FROM (SELECT SUM(x) AS s, y FROM t GROUP BY y) AS d",
    f"SELECT * FROM (SELECT SUM(x), y FROM t GROUP BY y) AS d",
    f"SELECT * FROM (SELECT x + 1, MAX(y) FROM t GROUP BY 1) AS d",
    f"SELECT d.* FROM (SELECT t.id FROM t) AS d JOIN (SELECT p.tid FROM p) AS e ON e.tid = d.id",
    f"SELECT * FROM (SELECT * EXCEPT (x) FROM t) AS d",
    f"SELECT * FROM (SELECT * REPLACE (x + 1 AS x) FROM t) AS d WHERE d.x > 1",
    f"SELECT d.x FROM (SELECT * EXCEPT (y) FROM t) AS d",
    f"SELECT * FROM (SELECT t.* FROM t JOIN p ON p.tid = t.id) AS d",
    f"SELECT * FROM (SELECT id FROM t UNION ALL SELECT k FROM u) AS d",
    f"SELECT * FROM ({{SELECT id AS a FROM t|SELECT x AS a FROM t}} UNION {{ALL|DISTINCT}} SELECT w AS a FROM u) AS d",
    f"SELECT * EXCEPT (x) FROM (SELECT id, x FROM t UNION ALL SELECT k, w FROM u) AS d",
    # _inline_ctes: references replaced by derived tables, with shadowing
    f"WITH c AS (SELECT id, x FROM t WHERE x > 0) SELECT c.id FROM c",
    f"WITH c AS (SELECT id, x FROM t WHERE x > 0) SELECT c.id, c2.x FROM c JOIN c AS c2 ON c2.id = c.id",
    f"WITH c AS (SELECT id, x FROM t) SELECT * FROM c",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3) SELECT * FROM c",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3) SELECT c.id FROM c WHERE c.x {{> 0|IS NULL}}",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3) SELECT COUNT(*) AS n FROM c",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3), e AS (SELECT * FROM c) SELECT * FROM e",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3), e AS (SELECT c.id FROM c) SELECT * FROM e",
    f"WITH t AS (SELECT id, x, y FROM t WHERE x > 0) SELECT COUNT(*) AS n FROM t",
    f"WITH t AS (SELECT id, x, y FROM t WHERE x > 0) SELECT t.id FROM t JOIN u ON u.k = t.y",
    f"WITH t AS (SELECT * FROM t WHERE x > 0) SELECT * FROM t",
    f"WITH t AS (SELECT * FROM t WHERE x > 0) SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS z WHERE z.id = t.id AND z.y IS NULL)",
    f"WITH u AS (SELECT id AS k, x AS v, y AS w FROM t) SELECT u.k FROM u JOIN t ON t.id = u.k",
    f"WITH t AS (SELECT id, x, y FROM t), u AS (SELECT k, w FROM u WHERE k IN (SELECT y FROM t)) SELECT * FROM u",
    f"WITH c AS (SELECT x AS id FROM t) SELECT t.id FROM t JOIN c ON c.id = t.id",
    f"WITH c AS (SELECT y, COUNT(*) AS n FROM t GROUP BY y) SELECT c.y, c.n FROM c WHERE c.n > 1",
    f"WITH c AS (SELECT y, COUNT(*) AS n FROM t GROUP BY y) SELECT c.y FROM c",
    f"WITH c AS (SELECT y, SUM(x) AS s FROM t GROUP BY y) SELECT SUM(c.s) AS s FROM c",
    f"WITH c AS (SELECT x, y FROM t) SELECT x FROM c WHERE EXISTS (SELECT 1 FROM c AS d WHERE d.y = c.x)",
    f"WITH c AS (SELECT x FROM t) SELECT (WITH c AS (SELECT w AS x FROM u) SELECT COUNT(*) FROM c) AS n FROM c",
    f"SELECT c.id FROM (WITH c AS (SELECT id FROM t WHERE x > 0) SELECT id FROM c) AS c",
    f"SELECT t.id FROM t WHERE t.x IN (WITH c AS (SELECT w FROM u) SELECT w FROM c)",
    f"WITH c AS (SELECT id, x FROM t) SELECT id FROM c UNION ALL SELECT id FROM c",
    f"WITH c AS (SELECT id, x FROM t) SELECT c.id, (SELECT COUNT(*) FROM c AS d WHERE d.x = c.x) AS n FROM c",
    f"WITH c(a, b) AS (SELECT id, x FROM t) SELECT a FROM c",
    f"WITH c AS (SELECT id, x FROM t) SELECT d.id FROM (SELECT c.id FROM c) AS d",
    # _inline_projection: a pass-through derived table is its base table
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d",
    f"SELECT d.x, u.v FROM (SELECT x, y FROM t) AS d {JOIN} u ON u.k = d.y",
    f"SELECT d.y FROM (SELECT x, y FROM t) AS d WHERE d.x > 0",
    f"SELECT COUNT(*) AS n FROM (SELECT x, y FROM t) AS d",
    f"SELECT d.a FROM (SELECT x AS a, y AS b FROM t) AS d",
    f"SELECT d.a, d.b FROM (SELECT x AS b, y AS a FROM t) AS d",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d JOIN p ON p.tid = d.y WHERE {{id|p.id|n > 0}} > 0",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d JOIN p ON p.tid = d.y WHERE {{id > 1|n > 0|b}}",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d WHERE EXISTS (SELECT 1 FROM u WHERE u.k = d.y AND {{u.w = x|w = y|w > 0}})",
    f"SELECT p.id FROM p WHERE EXISTS (SELECT 1 FROM (SELECT x, y FROM t) AS d WHERE d.y = p.tid AND {{id > 0|d.x > 0}})",
    f"SELECT (SELECT COUNT(*) FROM (SELECT x, y FROM t) AS d WHERE d.y = p.tid {{|AND tid IS NULL}}) AS n FROM p",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d, (SELECT id, tid FROM p) AS e WHERE e.tid = d.y",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS d LEFT JOIN (SELECT k, w FROM u) AS e ON e.k = d.y WHERE e.w {{IS NULL|> 0}}",
    f"SELECT d.x FROM (SELECT x, y FROM t) AS t",
    f"SELECT t.x FROM (SELECT x, y FROM t) AS t JOIN u ON u.k = t.y",
    f"SELECT u.k FROM (SELECT k, v FROM u) AS t JOIN u ON u.k = t.k",
    f"SELECT d.x FROM (SELECT t.x, t.y FROM t AS t) AS d",
    f"SELECT d.x FROM (SELECT t.x FROM t AS q) AS d",
    f"SELECT x FROM (SELECT x FROM t) AS d",
    f"SELECT d.x FROM (SELECT x, x FROM t) AS d",
    # _inline_expression_projection: computed columns over one table fold into the reader
    f"SELECT d.z FROM (SELECT x + 1 AS z FROM t) AS d WHERE d.z > 2",
    f"SELECT d.z, {{COUNT(*)|SUM(d.y)}} AS c FROM (SELECT x * 2 AS z, y FROM t) AS d GROUP BY d.z",
    f"SELECT d.z, u.v FROM (SELECT {{x + 1|COALESCE(x, 0)|x IS NULL|1|CASE WHEN x > 0 THEN 1 END|x * y}} AS z, y FROM t) AS d {JOIN} u ON u.k = d.y",
    f"SELECT d.z, p.n FROM (SELECT {{x + 1|COALESCE(x, 0)|x IS NULL|1|x > 0|CAST(x AS FLOAT64)}} AS z, id FROM t) AS d {JOIN} p ON p.tid = d.id",
    f"SELECT t.id, d.z FROM t {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} (SELECT {{k + 1|COALESCE(k, 0)|k IS NULL|7|w > 0|w IS NOT NULL}} AS z, k FROM u) AS d ON d.k = t.y",
    f"SELECT d.z, d.w FROM (SELECT x + 1 AS z, x + 1 AS w FROM t) AS d",
    f"SELECT d.z FROM (SELECT x + 1 AS z, y AS x FROM t) AS d WHERE d.x > 0",
    f"SELECT d.z FROM (SELECT y AS x, x + 1 AS z FROM t) AS d WHERE d.x > 0",
    f"SELECT d.z FROM (SELECT x + y AS z, x AS y FROM t) AS d",
    f"SELECT d.z FROM (SELECT t.x + 1 AS z FROM t AS t) AS d JOIN p AS t ON t.tid = d.z",
    f"SELECT z FROM (SELECT x + 1 AS z FROM t) AS d",
    f"SELECT d.z FROM (SELECT x + 1 AS z FROM t) AS d, (SELECT 2 AS z) AS e WHERE d.z > e.z",
    # _merge_spj_source: a filtering / joining derived table folds into the grouped select above
    f"SELECT d.y, {{COUNT(*)|SUM(d.x)|MAX(d.x)}} AS c FROM (SELECT x, y FROM t WHERE {{x > 0|y IS NOT NULL|x = y}}) AS d GROUP BY d.y",
    f"SELECT {{COUNT(*)|SUM(d.x)|COUNT(d.x)}} AS c FROM (SELECT x, y FROM t WHERE x > 0) AS d WHERE d.y {{> 0|IS NULL}}",
    f"SELECT d.k, SUM(d.w) AS c FROM (SELECT t.y AS k, u.w FROM t JOIN u ON u.k = t.y WHERE u.w > 0) AS d GROUP BY d.k",
    f"SELECT SUM(d.x) AS s FROM (SELECT x, y FROM t WHERE {{FALSE|1 = 0|x > 0 AND x < 0}}) AS d",
    f"SELECT COUNT(*) AS c FROM (SELECT x FROM t WHERE y IN (SELECT k FROM u)) AS d",
    f"SELECT COUNT(*) AS c FROM (SELECT x FROM t WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.y)) AS d",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT y FROM t WHERE x > 0) AS d JOIN u ON u.k = d.y GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT y FROM t WHERE x > 0) AS d JOIN (SELECT k FROM u WHERE w > 0) AS e ON e.k = d.y GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT t.y FROM t LEFT JOIN p ON p.tid = t.id WHERE t.x > 0) AS d GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT y AS q, y FROM t WHERE x > 0) AS d GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT x AS y, y AS x FROM t WHERE x > 0) AS d GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT y FROM t WHERE x > 0 ORDER BY y LIMIT 2) AS d GROUP BY d.y",
    f"SELECT d.y, COUNT(*) AS c FROM (SELECT DISTINCT y FROM t WHERE x > 0) AS d GROUP BY d.y",
    f"SELECT t.y, COUNT(*) AS c FROM (SELECT y, id FROM t WHERE x > 0) AS t GROUP BY t.y",
    f"SELECT y, COUNT(*) AS c FROM (SELECT y, x FROM t WHERE x > 0) AS d GROUP BY y",
    # _prune_derived: unread outputs go; a global aggregate keeps one, DISTINCT / LIMIT keep everything
    f"SELECT d.k FROM (SELECT t.y AS k, COUNT(*) AS c, MAX(t.x) AS m FROM t GROUP BY t.y) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT t.y AS k, SUM(t.x) AS s FROM t GROUP BY t.y) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT {{SUM(t.x)|COUNT(*)}} AS s, {{MAX(t.x)|MIN(t.y)}} AS m FROM t) AS d",
    f"SELECT 1 AS n FROM (SELECT {{SUM(t.x)|COUNT(*)}} AS s, t.y FROM t GROUP BY t.y) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT DISTINCT t.x, t.y FROM t) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT t.x, t.y FROM t ORDER BY t.x LIMIT 3) AS d",
    f"SELECT d.k FROM (SELECT t.y AS k, SUM(t.x) AS s FROM t GROUP BY t.y) AS d JOIN (SELECT p.tid AS k, COUNT(*) AS c FROM p GROUP BY p.tid) AS e ON e.k = d.k",
    f"SELECT d.k FROM (SELECT t.y AS k, t.x AS j, t.id FROM t) AS d WHERE d.j > 0",
    f"SELECT COUNT(*) AS n FROM (SELECT t.y AS k, t.x AS k FROM t) AS d",
    f"SELECT d.k FROM (SELECT t.y AS k, t.x AS k FROM t) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT {{id|x|y}} AS a, id, x FROM t WHERE x > 0) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT COUNT(*) AS a FROM t UNION ALL SELECT COUNT(*) AS a FROM u) AS d",
    f"SELECT d.a FROM (SELECT id AS a, x AS b FROM t UNION ALL SELECT k AS a, w AS b FROM u) AS d",
    # _canonicalize_union_source: a derived UNION ALL read by columns
    f"SELECT d.a, d.b FROM (SELECT t.y AS a, t.x AS b FROM t UNION ALL SELECT u.k AS a, u.w AS b FROM u) AS d",
    f"SELECT d.b, d.a FROM (SELECT t.y AS a, t.x AS b FROM t UNION ALL SELECT u.w AS q, u.k AS r FROM u) AS d",
    f"SELECT SUM(d.a) AS s, MAX(d.b) AS m FROM (SELECT t.y AS a, t.x AS b FROM t WHERE t.x > 0 UNION ALL SELECT u.k, u.w FROM u) AS d",
    f"SELECT d.a FROM (SELECT t.x AS a, t.y AS a2 FROM t UNION ALL SELECT u.w AS a, u.k AS a2 FROM u UNION ALL SELECT p.n AS a, p.tid AS a2 FROM p) AS d WHERE d.a2 > 0",
    f"SELECT * FROM (SELECT t.y AS a, t.x AS b FROM t UNION ALL SELECT u.k, u.w FROM u) AS d WHERE d.a > 0",
    f"SELECT d.a FROM (SELECT t.y AS a FROM t UNION ALL SELECT u.k AS a FROM u) AS d JOIN u ON u.k = d.a",
    f"SELECT COUNT(*) AS n FROM (SELECT t.y AS a FROM t AS q UNION ALL SELECT q.k AS a FROM u AS q) AS d",
    f"SELECT d.a FROM (SELECT y AS a, x AS b FROM t UNION ALL SELECT k, w FROM u) AS d",
    f"SELECT COUNT(DISTINCT d.a) AS n FROM (SELECT t.y AS a FROM t UNION ALL SELECT u.k AS a FROM u) AS d",
    f"SELECT d.a, COUNT(*) AS n FROM (SELECT t.y AS a FROM t UNION ALL SELECT u.k AS a FROM u) AS d GROUP BY d.a",
    # _name_derived_columns / _order_grouped_columns: unnamed outputs and the order of a grouped derived table
    f"SELECT * FROM (SELECT MIN(x), MAX(x) FROM t) AS d",
    f"SELECT d.* FROM (SELECT y, COUNT(*), SUM(x) FROM t GROUP BY y) AS d",
    f"SELECT d.k, d.c FROM (SELECT SUM(x) AS s, COUNT(*) AS c, y AS k FROM t GROUP BY y) AS d JOIN (SELECT COUNT(*) AS c, SUM(x) AS s, y AS k FROM t GROUP BY y) AS e ON e.k = d.k",
    f"SELECT d.k, d.s FROM (SELECT SUM(x) AS s, y AS k, COUNT(*) AS c FROM t GROUP BY y) AS d",
    f"SELECT * FROM (SELECT SUM(x) AS s, y AS k FROM t GROUP BY y) AS d",
    f"SELECT d.k FROM (SELECT SUM(x) AS s, y AS k, x AS j FROM t GROUP BY y, x ORDER BY s) AS d",
    f"SELECT * FROM (SELECT SUM(x) AS s, y AS k, x AS j FROM t GROUP BY y, x) AS d",
]


def cases(seed: int, count: int) -> list[dict]:
    return expand(TEMPLATES, seed, count, "derived_tables")
