"""Derived-table rewrites that fire rarely, and the stress cases around them: a derived table read through IN / EXISTS
(``_unwrap_projection``), a union nested in a union (``_flatten_unions``), a derived ORDER BY .. LIMIT whose ORDER BY
names an output alias (``_lift_limit_derived``), unnamed derived outputs (``_name_derived_columns``), bare columns of an
enclosing query read next to a derived table (``_checked_qualification``), ``USING`` joins (``_using_to_on`` and
``using_to_on_unqualified``), a grouped select with window functions over a derived outer join
(``lift_derived_expressions``), redundant row clauses (``trim_redundant_row_clauses``) and named windows.

Each group also holds near misses: shadowed aliases, a CTE with a table's name, derived outputs that swap the names of
base columns, duplicate output names, ``SELECT *`` with EXCEPT / REPLACE, ORDER BY / LIMIT inside a derived table, and
correlated references that a rewrite must keep pointing at the same source."""

from ._base import expand

JOIN = "{JOIN|LEFT JOIN|RIGHT JOIN|FULL JOIN}"
GROUPED = "(SELECT y AS a, {SUM(x)|COUNT(*)|MAX(x)|MIN(x)} AS b FROM t GROUP BY y {|HAVING COUNT(*) > 1})"

TEMPLATES = [
    # _unwrap_projection (only inside IN / EXISTS, where _fold_filter_into_grouping leaves the derived table alone)
    f"SELECT t.id FROM t WHERE t.y {{IN|NOT IN}} (SELECT d.{{a|b}} FROM {GROUPED} AS d)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT d.{{a|b}} FROM {GROUPED} AS d WHERE d.a = t.x)",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT d.a FROM (SELECT {{SUM(x)|COUNT(*)|MAX(x)}} AS a, COUNT(y) AS b FROM t {{|WHERE x > 100}}) AS d)",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT 1 FROM (SELECT {{SUM(x)|COUNT(*)}} AS a FROM t {{|WHERE x > 100}}) AS d)",
    f"SELECT t.id FROM t WHERE {{EXISTS|NOT EXISTS}} (SELECT 1 FROM (SELECT {{SUM(x)|COUNT(*)}} AS a FROM t WHERE x > 100) AS d)",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT d.a FROM (SELECT y AS a, y AS b FROM t GROUP BY y) AS d)",
    f"SELECT t.id FROM t WHERE t.y IN (SELECT d.k FROM (SELECT u.k AS k, COUNT(*) AS c FROM u GROUP BY u.k) AS d)",
    # _flatten_unions
    f"SELECT id FROM t UNION DISTINCT (SELECT k FROM u UNION DISTINCT SELECT tid FROM p)",
    f"(SELECT id FROM t UNION DISTINCT SELECT k FROM u) UNION DISTINCT SELECT tid FROM p",
    f"SELECT id FROM t UNION ALL (SELECT k FROM u UNION ALL SELECT tid FROM p)",
    f"SELECT id FROM t UNION DISTINCT (SELECT k FROM u UNION ALL SELECT tid FROM p)",
    f"SELECT id FROM t UNION ALL (SELECT k FROM u UNION DISTINCT SELECT tid FROM p)",
    f"(SELECT id FROM t UNION DISTINCT SELECT k FROM u) UNION ALL SELECT tid FROM p",
    f"(SELECT id FROM t UNION ALL SELECT k FROM u) UNION DISTINCT SELECT tid FROM p",
    f"SELECT id FROM t UNION DISTINCT SELECT d.a FROM (SELECT k AS a FROM u UNION DISTINCT SELECT tid AS a FROM p) AS d",
    f"SELECT d.a FROM (SELECT k AS a FROM u UNION DISTINCT SELECT tid AS a FROM p) AS d UNION DISTINCT SELECT id FROM t",
    f"SELECT id FROM t UNION ALL SELECT d.a FROM (SELECT k AS a FROM u UNION ALL SELECT tid AS a FROM p) AS d",
    f"SELECT id FROM t UNION DISTINCT SELECT d.a FROM (SELECT k AS a FROM u UNION ALL SELECT tid AS a FROM p) AS d",
    f"SELECT id FROM t UNION ALL SELECT d.a FROM (SELECT k AS a FROM u UNION DISTINCT SELECT tid AS a FROM p) AS d",
    f"SELECT id, x FROM t UNION DISTINCT SELECT d.{{a, d.b|b, d.a}} FROM (SELECT k AS a, w AS b FROM u UNION DISTINCT SELECT tid, n FROM p) AS d",
    f"SELECT id FROM t UNION DISTINCT SELECT d.a FROM (SELECT k AS a FROM u UNION DISTINCT SELECT tid AS a FROM p) AS d WHERE d.a > 0",
    f"SELECT id FROM t UNION DISTINCT SELECT d.a FROM (SELECT k AS a, w FROM u UNION DISTINCT SELECT tid AS a, n FROM p) AS d",
    f"SELECT id FROM t UNION DISTINCT SELECT d.a FROM (SELECT k AS a FROM u UNION DISTINCT SELECT tid AS a FROM p) AS d, u AS z",
    f"SELECT id FROM t UNION DISTINCT (SELECT k FROM u UNION DISTINCT SELECT tid FROM p ORDER BY 1 LIMIT 2)",
    f"SELECT id FROM t UNION DISTINCT (SELECT k FROM u UNION DISTINCT SELECT tid FROM p) UNION DISTINCT SELECT w FROM u",
    f"SELECT id FROM t UNION DISTINCT (SELECT k FROM u UNION DISTINCT (SELECT tid FROM p UNION DISTINCT SELECT w FROM u))",
    f"SELECT COUNT(*) AS n FROM (SELECT id FROM t UNION ALL (SELECT k FROM u UNION ALL SELECT tid FROM p)) AS d",
    f"SELECT d.a FROM (SELECT id AS a FROM t UNION DISTINCT (SELECT k FROM u UNION DISTINCT SELECT tid FROM p)) AS d WHERE d.a > 0",
    f"SELECT id FROM t WHERE id IN (SELECT k FROM u UNION DISTINCT (SELECT tid FROM p UNION DISTINCT SELECT w FROM u))",
    # _lift_limit_derived: the derived ORDER BY names an output alias inside an expression (limit_rule declines those)
    f"SELECT d.id, d.q FROM (SELECT id, x AS q FROM t ORDER BY {{q + 1|-q|COALESCE(q, 0)|q * q|ABS(q)}}, id LIMIT {{1|3}}) AS d",
    f"SELECT d.q, d.id FROM (SELECT id, x AS q FROM t ORDER BY {{q + 1|-q}} {{|DESC}}, id LIMIT 3 OFFSET {{0|1}}) AS d",
    f"SELECT d.id AS q, d.q AS z FROM (SELECT id, x AS q FROM t ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.q AS id, d.id AS q FROM (SELECT id, x AS q FROM t ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.id FROM (SELECT id, x AS q FROM t ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.id, d.q FROM (SELECT id, x + y AS q FROM t ORDER BY q * 2, id LIMIT 3) AS d",
    f"SELECT d.q FROM (SELECT id, SUM(x) AS q FROM t GROUP BY id ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.q FROM (SELECT y, SUM(x) AS q FROM t GROUP BY y ORDER BY q + 1, y LIMIT 3) AS d",
    f"SELECT d.y FROM (SELECT y, SUM(x) AS q FROM t GROUP BY y ORDER BY q + 1, y LIMIT 3) AS d",
    f"SELECT d.id FROM (SELECT id, x FROM t ORDER BY x, id LIMIT CAST(3 AS INT64)) AS d",
    f"SELECT d.id, d.x FROM (SELECT id, x FROM t ORDER BY x DESC, id {{LIMIT 2|LIMIT 2 OFFSET 1}}) AS d",
    f"SELECT d.id, d.id AS again FROM (SELECT id, x AS q FROM t ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.q FROM (SELECT x AS q, x AS r FROM t ORDER BY q + 1, id LIMIT 3) AS d",
    f"SELECT d.q FROM (SELECT id AS q, x AS id FROM t ORDER BY id + 1, q LIMIT 3) AS d",
    f"SELECT d.id FROM (SELECT x AS id, id AS x FROM t ORDER BY x + 1, id LIMIT 3) AS d",
    f"SELECT d.q FROM (SELECT x AS q FROM t ORDER BY q + 1, x LIMIT 3) AS d",
    # _name_derived_columns: unnamed outputs of a derived table (the generated names must not capture a real column)
    f"SELECT d.a FROM (SELECT y AS a, x + 1 FROM t) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT x + 1, MIN(y) FROM t GROUP BY x) AS d",
    f"SELECT * FROM (SELECT x + 1, y FROM t) AS d",
    f"SELECT d.* FROM (SELECT MAX(x), y FROM t GROUP BY y) AS d WHERE d.y > 0",
    f"SELECT d.a, e.a AS b FROM (SELECT y AS a, x + 1 FROM t) AS d {JOIN} (SELECT k AS a, w * 2 FROM u) AS e ON e.a = d.a",
    f"SELECT d.kqc0 FROM (SELECT x + 1, y AS kqc0 FROM t) AS d",
    f"SELECT d.a FROM (SELECT y AS a, {{x + 1|CAST(x AS FLOAT64)|COALESCE(x, 0)|x > 0|s}} FROM t WHERE x > 0 ORDER BY y LIMIT 3) AS d",
    f"SELECT d.a FROM (SELECT y AS a, COUNT(*) FROM t GROUP BY y HAVING COUNT(*) > 1) AS d",
    # _checked_qualification (_qualify_correlated_columns): a bare column of the enclosing query next to a derived table
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT id AS i FROM t AS t2) AS d WHERE d.i = y)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT id AS i, y AS j FROM t AS t2) AS d WHERE d.j = y)",
    f"SELECT p.id FROM p WHERE EXISTS (SELECT 1 FROM (SELECT id AS i FROM p AS p2) AS d WHERE d.i = tid)",
    f"SELECT p.id FROM p WHERE {{tid|n}} IN (SELECT d.i FROM (SELECT id AS i FROM p AS p2) AS d)",
    f"SELECT t.id, (SELECT MAX(d.w) FROM (SELECT w, k FROM u) AS d WHERE d.k = y) AS m FROM t",
    f"SELECT t.id, (SELECT COUNT(*) FROM (SELECT id AS i FROM t AS t2) AS d WHERE d.i < x) AS m FROM t",
    f"SELECT t.id FROM t WHERE x > (SELECT COUNT(*) FROM (SELECT tid FROM p AS p2) AS d WHERE d.tid = y)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT id AS i FROM t) AS d WHERE d.i = id)",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT id AS i FROM t AS t2 WHERE t2.x > t.x) AS d WHERE d.i = t.y)",
    f"SELECT p.id FROM p WHERE EXISTS (SELECT 1 FROM (SELECT id AS i, x AS xx FROM t) AS d JOIN u ON u.k = d.i WHERE u.w = n)",
    f"SELECT t.id FROM t JOIN p ON p.tid = t.id WHERE EXISTS (SELECT 1 FROM (SELECT id AS i FROM p AS q) AS d WHERE d.i = n)",
    # USING joins (t and p share id; u joins through a renamed derived table)
    f"SELECT id, x, n FROM t {JOIN} p USING (id)",
    f"SELECT * FROM t {JOIN} p USING (id)",
    f"SELECT t.id, p.id AS pid, x FROM t {JOIN} p USING (id)",
    f"SELECT p.id, t.x FROM t {JOIN} p USING (id)",
    f"SELECT d.id, d.x FROM (SELECT id, x FROM t {JOIN} p USING (id)) AS d",
    f"SELECT d.id FROM (SELECT * FROM t {JOIN} p USING (id)) AS d",
    f"SELECT d.n FROM (SELECT * EXCEPT (id) FROM t {JOIN} p USING (id)) AS d",
    f"SELECT id FROM t {JOIN} (SELECT tid AS id, n FROM p) AS e USING (id)",
    f"SELECT * FROM t {JOIN} (SELECT k AS id, w FROM u) AS e USING (id)",
    f"SELECT id, x, w FROM t {JOIN} (SELECT * FROM u) AS e USING (id)",
    f"SELECT id, x, tid FROM t {JOIN} (SELECT * FROM p) AS e USING (id)",
    f"SELECT x, n FROM t {JOIN} (SELECT * FROM p) AS e USING (id)",
    f"SELECT * FROM t {JOIN} (SELECT id, y AS x FROM t) AS e USING (id, x)",
    f"SELECT id, x, n, w FROM t {{JOIN|FULL JOIN|LEFT JOIN}} p USING (id) {{JOIN|LEFT JOIN|FULL JOIN}} (SELECT k AS id, w FROM u) AS e USING (id)",
    f"SELECT * FROM t {{JOIN|FULL JOIN|LEFT JOIN}} p USING (id) {{JOIN|LEFT JOIN|FULL JOIN}} (SELECT k AS id, w FROM u) AS e USING (id)",
    f"SELECT id, COUNT(*) AS c FROM t {JOIN} p USING (id) WHERE id > 1 GROUP BY id HAVING id < 100 ORDER BY id",
    f"SELECT id AS z, COUNT(n) AS c FROM t {JOIN} p USING (id) GROUP BY id",
    f"SELECT id FROM t {JOIN} p USING (id) WHERE EXISTS (SELECT 1 FROM u WHERE u.k = id)",
    f"SELECT t.id FROM t {JOIN} p USING (id) WHERE EXISTS (SELECT 1 FROM u WHERE u.k = t.id)",
    f"SELECT * EXCEPT (id) FROM t {JOIN} p USING (id)",
    f"SELECT * REPLACE (x + 1 AS x) FROM t {JOIN} p USING (id)",
    f"SELECT t.* EXCEPT (x), n FROM t {JOIN} p USING (id)",
    f"SELECT x, COUNT(*) AS c FROM t {JOIN} p USING (id) GROUP BY x ORDER BY c, x LIMIT 3",
    f"SELECT SUM(n) AS s FROM t {JOIN} p USING (id) WHERE id IS NULL",
    f"SELECT d.id, d.k FROM (SELECT id, k FROM t {JOIN} (SELECT k, w FROM u) AS e USING (k)) AS d",
    f"SELECT id FROM (SELECT id, x FROM t) AS a {JOIN} (SELECT id, n FROM p) AS b USING (id)",
    f"SELECT a.id, b.id AS id2 FROM (SELECT id, x FROM t) AS a {JOIN} (SELECT id, n FROM p) AS b USING (id)",
    # lift_derived_expressions: a grouped select with windows over a derived outer join (outer_join_rules declines those)
    f"SELECT d.z, COUNT(*) AS c, RANK() OVER (ORDER BY COUNT(*)) AS r FROM (SELECT t.x + 1 AS z, p.id AS pid FROM t {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} p ON p.tid = t.id) AS d GROUP BY d.z",
    f"SELECT d.z, {{COUNT(d.pid)|COUNT(*)|SUM(d.pid)}} AS c FROM (SELECT {{t.x * 2|COALESCE(t.x, 0)|t.x + t.y|t.x IS NULL}} AS z, p.id AS pid FROM t LEFT JOIN p ON p.tid = t.id) AS d GROUP BY d.z QUALIFY RANK() OVER (ORDER BY COUNT(*)) <= 2",
    f"SELECT d.z, MAX(d.pid) AS m, SUM(COUNT(*)) OVER () AS total FROM (SELECT t.y - 1 AS z, p.id AS pid FROM t LEFT JOIN p ON p.tid = t.id) AS d GROUP BY d.z",
    f"SELECT d.z, COUNT(*) AS c, ROW_NUMBER() OVER (ORDER BY d.z) AS r FROM (SELECT t.x + 1 AS z, p.n AS n FROM t LEFT JOIN p ON p.tid = t.id AND p.n > 0) AS d GROUP BY d.z",
    # trim_redundant_row_clauses
    f"SELECT COUNT(*) AS c FROM t {{ORDER BY 1|}} LIMIT {{1|2|5}}",
    f"SELECT * FROM (SELECT {{SUM(x)|COUNT(*)}} AS s FROM t ORDER BY 1 LIMIT {{1|2}}) AS d",
    f"SELECT COUNT(*) AS c FROM t UNION ALL SELECT COUNT(*) FROM u LIMIT {{1|2|3}}",
    f"SELECT COUNT(*) AS c FROM t UNION DISTINCT SELECT COUNT(*) FROM u LIMIT {{1|2|3}}",
    f"SELECT COUNT(*) AS c FROM t EXCEPT DISTINCT SELECT COUNT(*) FROM u LIMIT {{1|2}}",
    f"SELECT MAX(x) AS m FROM t WHERE x > {{0|100}} ORDER BY m LIMIT 1 OFFSET {{0|1}}",
    f"SELECT d.c FROM (SELECT COUNT(*) AS c FROM t LIMIT {{0|1|2}}) AS d LIMIT 1",
    f"SELECT d.k FROM (SELECT DISTINCT y AS k FROM t LIMIT 2) AS d LIMIT {{1|2|3}}",
    f"SELECT d.c FROM (SELECT COUNT(*) AS c FROM t) AS d ORDER BY d.c LIMIT {{1|2}}",
    f"SELECT d.c FROM (SELECT COUNT(*) AS c FROM t) AS d WHERE d.c {{> 0|= 0}} LIMIT 1",
    f"SELECT d.c FROM (SELECT x AS c FROM t LIMIT 3) AS d LIMIT {{1|3|5}}",
    f"SELECT 1 AS one LIMIT {{0|1|2}}",
    f"SELECT SUM(x) OVER () AS s FROM t LIMIT 1",
    f"SELECT t.id FROM t WHERE x IN (SELECT k FROM u ORDER BY k LIMIT {{1|2}})",
    f"SELECT t.id FROM t WHERE x IN (SELECT MAX(w) FROM u ORDER BY 1 LIMIT {{1|2}})",
    # inline_named_windows
    f"SELECT id, SUM(x) OVER w AS s FROM t WINDOW w AS (PARTITION BY y ORDER BY id)",
    f"SELECT id, SUM(x) OVER w AS s, MAX(x) OVER w AS m FROM t WINDOW w AS (PARTITION BY y)",
    f"SELECT id, SUM(x) OVER (w ORDER BY id) AS s FROM t WINDOW w AS (PARTITION BY y)",
    f"SELECT d.id, d.s FROM (SELECT id, SUM(x) OVER w AS s FROM t WINDOW w AS (PARTITION BY y ORDER BY id)) AS d WHERE d.id > 1",
    # shadowed aliases, CTEs that shadow tables, swapped names (the rewrite must keep reading the same source)
    f"SELECT d.x FROM (SELECT DISTINCT y AS x, x AS y FROM t) AS d WHERE d.x {{> 0|IS NULL}}",
    f"SELECT d.x FROM (SELECT y AS x, x AS y FROM t GROUP BY y, x) AS d WHERE d.x > 0 AND d.y {{> 0|IS NULL}}",
    f"SELECT d.x, d.y FROM (SELECT y AS x, x AS y FROM t WHERE x > 0) AS d JOIN u ON u.k = d.x",
    f"SELECT d.x, COUNT(*) AS c FROM (SELECT y AS x, x AS y FROM t WHERE x > 0) AS d GROUP BY d.x",
    f"SELECT d.y FROM (SELECT y AS x, x AS y FROM t ORDER BY x, id LIMIT 3) AS d WHERE d.x > 0",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM (SELECT k, w FROM u) AS t WHERE t.k = 1)",
    f"SELECT t.id FROM t WHERE x IN (SELECT t.w FROM (SELECT w FROM u) AS t)",
    f"SELECT t.id FROM (SELECT id, x FROM t WHERE x > 0) AS t WHERE EXISTS (SELECT 1 FROM t WHERE t.y = 1)",
    f"SELECT t.id, u.v FROM (SELECT id, y FROM t) AS t {JOIN} u ON u.k = t.y",
    f"SELECT u.k FROM (SELECT k, w FROM u WHERE w > 0) AS u {JOIN} t ON t.y = u.k",
    f"WITH t AS (SELECT * EXCEPT (y) FROM t) SELECT * FROM t",
    f"WITH t AS (SELECT id, x FROM t ORDER BY x, id LIMIT 3) SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM t AS z WHERE z.x = t.x)",
    f"WITH c AS (SELECT id, x FROM t) SELECT * EXCEPT (x) FROM c JOIN u ON u.k = c.id",
    f"WITH c AS (SELECT * REPLACE (x + 1 AS x) FROM t) SELECT c.id, c.x FROM c WHERE c.x > 1",
    f"WITH c AS (SELECT y, x FROM t), d AS (SELECT y, COUNT(*) AS n FROM c GROUP BY y) SELECT d.y, d.n FROM d JOIN c ON c.y = d.y",
    f"WITH c AS (SELECT id, x FROM t) SELECT c.id FROM c WHERE c.x IN (WITH c AS (SELECT w FROM u) SELECT w FROM c)",
    f"WITH c AS (SELECT id, x FROM t ORDER BY id LIMIT 3), d AS (SELECT id FROM c WHERE x > 0) SELECT * FROM d",
    f"WITH c AS (SELECT x AS id, id AS x FROM t) SELECT * FROM c WHERE c.id > 0",
    # SELECT * with EXCEPT / REPLACE over derived tables, duplicates and joins
    f"SELECT * EXCEPT ({{x|y|x, y}}) FROM (SELECT id, x, y FROM t ORDER BY id LIMIT 3) AS d",
    f"SELECT * REPLACE ({{x + 1 AS x|COALESCE(y, 0) AS y}}) FROM (SELECT id, x, y FROM t WHERE x > 0) AS d WHERE d.id > 0",
    f"SELECT d.* EXCEPT (x) FROM (SELECT id, x, y FROM t) AS d {JOIN} u ON u.k = d.y",
    f"SELECT * EXCEPT (id) FROM (SELECT id, x FROM t) AS d {JOIN} (SELECT tid AS id, n FROM p) AS e ON e.id = d.id",
    f"SELECT d.*, e.n FROM (SELECT * REPLACE (id + 1 AS id) FROM t) AS d JOIN p AS e ON e.tid = d.id",
    f"SELECT * FROM (SELECT * EXCEPT (x) FROM (SELECT * REPLACE (x + 1 AS y) FROM t) AS a) AS b",
    f"SELECT COUNT(*) AS n FROM (SELECT * EXCEPT (x) FROM t WHERE x > 0) AS d WHERE d.y > 0",
    # duplicates and correlation inside derived tables
    f"SELECT d.c FROM (SELECT id, (SELECT COUNT(*) FROM p WHERE p.tid = t.id) AS c FROM t) AS d WHERE d.c > 1",
    f"SELECT d.z FROM (SELECT x + 1 AS z FROM t) AS d WHERE EXISTS (SELECT 1 FROM u WHERE u.w = d.z)",
    f"SELECT d.z FROM (SELECT x + 1 AS z, y FROM t) AS d WHERE d.z > (SELECT MIN(w) FROM u WHERE u.k = d.y)",
    f"SELECT d.s FROM (SELECT id, (SELECT SUM(n) FROM p WHERE p.tid = t.id) AS s FROM t) AS d WHERE d.s IS NULL",
    f"SELECT d.id FROM (SELECT id, x FROM t WHERE x IN (SELECT w FROM u WHERE u.k = t.y)) AS d WHERE d.x > 0",
    f"SELECT d.x FROM (SELECT x, x FROM t) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT x, x FROM t) AS d",
    f"SELECT COUNT(*) AS n FROM (SELECT x AS a, y AS a FROM t) AS d",
    f"SELECT d.a FROM (SELECT x AS a, y AS a FROM t WHERE x > 0) AS d",
    f"SELECT * FROM (SELECT x AS a, x AS a FROM t ORDER BY x LIMIT 2) AS d",
]


def cases(seed: int, count: int) -> list[dict]:
    return expand(TEMPLATES, seed, count, "derived_stress")
