"""Outer-join rules: LEFT/RIGHT/FULL to inner, indicator joins, padded-side filters, exists in ON, null-extended
filters, grouped outer joins and foreign-key joins."""

from ._base import expand

JOIN = "{LEFT JOIN|RIGHT JOIN|FULL JOIN|JOIN}"
WHERE = "{|WHERE p.b|WHERE p.n > 0|WHERE p.id IS NULL|WHERE p.id IS NOT NULL|WHERE t.x > 0|WHERE p.tid = t.id|WHERE COALESCE(p.n, 0) > 0|WHERE p.b IS NULL OR t.x > 0}"
ON = "{p.tid = t.id|p.tid = t.id AND p.n > 0|p.tid = t.id AND t.x > 0|p.tid = t.id AND p.b|p.tid = t.x}"

TEMPLATES = [
    f"SELECT t.id, p.n FROM t {JOIN} p ON {ON} {WHERE}",
    f"SELECT t.id, p.id AS pid FROM t {JOIN} p ON {ON} {WHERE}",
    f"SELECT COUNT(*) AS c, COUNT(p.id) AS d FROM t {JOIN} p ON {ON} {WHERE}",
    f"SELECT t.id, COUNT(p.id) AS c, SUM(p.n) AS s FROM t {JOIN} p ON {ON} {WHERE} GROUP BY t.id",
    f"SELECT t.x, COUNT(*) AS c FROM t {JOIN} p ON {ON} GROUP BY t.x {{|HAVING COUNT(p.id) > 0|HAVING SUM(p.n) > 0}}",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON} WHERE p.id IS NULL",
    f"SELECT t.id FROM t WHERE NOT EXISTS (SELECT 1 FROM p WHERE {{p.tid = t.id|p.tid = t.id AND p.b}})",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM p WHERE p.tid = t.id {{|AND p.n > 0}})",
    f"SELECT t.id, u.v FROM t {{LEFT JOIN|JOIN}} p ON {ON} {{LEFT JOIN|JOIN|RIGHT JOIN}} u ON {{u.k = p.tid|u.k = t.y|u.w = p.id|u.k = COALESCE(p.tid, 0)}}",
    f"SELECT t.id, q.c FROM t {{LEFT JOIN|JOIN}} (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS q ON q.tid = t.id {{|WHERE q.c > 0|WHERE q.c IS NULL|WHERE COALESCE(q.c, 0) = 0}}",
    f"SELECT t.id, q.n FROM t LEFT JOIN (SELECT p.* FROM p WHERE {{p.b|p.n > 0}}) AS q ON q.tid = t.id",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id AND {{EXISTS (SELECT 1 FROM u WHERE u.k = 1)|EXISTS (SELECT 1 FROM u WHERE u.k = t.y)|NOT EXISTS (SELECT 1 FROM u)}}",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE t.id = {{1|2|p.tid}}",
    f"SELECT a.id, b.id AS bid FROM t AS a {{LEFT JOIN|FULL JOIN|JOIN}} t AS b ON {{a.id = b.id|a.x = b.y|a.id = b.id AND a.x > 0}} {{|WHERE b.id IS NULL|WHERE b.id IS NOT NULL}}",
    f"SELECT t.id, COUNT(*) AS c FROM t {{LEFT JOIN|FULL JOIN}} p ON p.tid = t.id GROUP BY t.id",
    f"SELECT p.tid, COUNT(*) AS c FROM p {{LEFT JOIN|JOIN}} t ON t.id = p.tid GROUP BY p.tid",
    f"SELECT DISTINCT t.id FROM t {{LEFT JOIN|JOIN}} p ON p.tid = t.id",
    f"SELECT t.id FROM t {{LEFT JOIN|JOIN}} p ON p.tid = t.id {{LEFT JOIN|JOIN}} u ON u.k = t.y",
    f"SELECT t.x FROM t JOIN p ON p.tid = t.id WHERE {{p.n IS NOT NULL|p.tid IS NOT NULL|TRUE}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p USING (id)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id AND p.id IS NULL",
    f"SELECT {{MAX|MIN|SUM|COUNT}}(p.n) AS a FROM t LEFT JOIN p ON p.tid = t.id WHERE t.x {{> 0|IS NULL}}",
    f"SELECT t.id FROM (SELECT t.id, t.x FROM t LEFT JOIN p ON p.tid = t.id) AS t WHERE t.x > 0",
    f"SELECT q.id FROM (t LEFT JOIN (p JOIN u ON u.k = p.tid) ON p.tid = t.id) AS q",
]


# Templates added for the outer-join rule family review (#518): one block per rule module, each with the
# NULL-accepting predicates, duplicate keys and three-valued-logic traps its guards have to stop.
SIDE = "{LEFT JOIN|RIGHT JOIN|FULL JOIN|JOIN}"
LR = "{LEFT JOIN|RIGHT JOIN}"
ON2 = "{p.tid = t.id|p.tid = t.id OR p.tid IS NULL|p.tid IS NOT DISTINCT FROM t.id|p.tid = t.id AND p.n IS NULL|p.n > t.x|t.x IS NULL OR p.tid = t.id|COALESCE(p.tid, 0) = COALESCE(t.id, 0)|TRUE|p.tid = t.id AND NOT p.b}"
PRED = "{p.n > 0|p.n IS NULL|p.n IS NOT NULL|COALESCE(p.n, 0) > 0|COALESCE(p.n, 0) = 0|p.n > 0 OR p.n IS NULL|p.n > 0 OR t.x > 0|p.n IS NULL OR t.x > 0|NOT (p.n > 0)|NOT (p.n IS NULL)|p.b IS NOT TRUE|p.b|NOT p.b|p.n BETWEEN 0 AND 5|p.n IN (1, 2)|p.n NOT IN (1, 2)|p.n = t.x|p.n IS DISTINCT FROM t.x|IFNULL(p.b, FALSE)|CAST(p.n AS INT64) > 0|p.n + 1 > 0|p.n * 0 = 0|CASE WHEN p.n > 0 THEN TRUE ELSE FALSE END|EXISTS (SELECT 1 FROM u WHERE u.k = p.tid)|NOT EXISTS (SELECT 1 FROM u WHERE u.k = p.tid)|p.tid IN (SELECT k FROM u)|p.tid NOT IN (SELECT k FROM u)|t.s LIKE 'a%'|p.tid = t.id}"

MORE = [
    # null_rejecting_joins: padded-side filters of every shape
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON {ON2} WHERE {PRED}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON {ON2} WHERE {PRED} AND {PRED}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON {ON2} WHERE ({PRED}) OR ({PRED})",
    f"SELECT COUNT(*) AS c FROM t LEFT JOIN p ON {ON2} WHERE {PRED}",
    f"SELECT t.id, p.n, u.v FROM t LEFT JOIN p ON {ON2} LEFT JOIN u ON {{u.k = p.tid|u.k = t.y|u.k = p.tid AND u.w > 0|u.k IS NULL}} WHERE {{u.v IS NOT NULL|u.w > 0|p.n > 0|u.v IS NULL|COALESCE(u.w, 0) > 0|u.w > 0 OR p.n > 0|u.w = p.n}}",
    f"SELECT t.id, p.n, u.v FROM t LEFT JOIN p ON {ON2} JOIN u ON {{u.k = p.tid|u.k = t.y|u.k IS NOT DISTINCT FROM p.tid|TRUE}} WHERE {{p.n > 0|TRUE|u.w > 0|p.n IS NULL}}",
    f"SELECT d.id, d.c FROM (SELECT t.id, {{p.n|COALESCE(p.n, 0)|p.n + 1|IFNULL(p.n, 1)|CASE WHEN p.n > 0 THEN 1 END|p.n IS NULL|CAST(p.n AS STRING)|CONCAT(t.s, CAST(p.n AS STRING))|t.x * p.n}} AS c FROM t LEFT JOIN p ON {ON2}) AS d WHERE {{d.c > 0|d.c IS NOT NULL|d.c IS NULL|d.c = 1|d.c|NOT d.c|d.c LIKE '%1%'|d.c > 0 OR d.id > 0|d.c IS NULL OR d.id = 1}}",
    f"SELECT c FROM (SELECT t.id, {{p.n|COALESCE(p.n, 0)|p.n + 1}} AS c FROM t LEFT JOIN p ON {ON2}) WHERE {{c > 0|c IS NOT NULL|c IS NULL}}",
    f"SELECT DISTINCT d.c FROM (SELECT t.id, p.n AS c FROM t LEFT JOIN p ON {ON2}) AS d WHERE d.c {{> 0|IS NOT NULL|IS NULL}}",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE EXISTS (SELECT 1 FROM u WHERE {{u.k = p.tid|u.k = p.tid AND u.w > 0|u.w = p.n|p.n IS NULL|p.n > 0 OR u.k = 1|COALESCE(p.n, 0) = u.w|p.n > 0 AND u.k = 1}})",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE EXISTS (SELECT COUNT(*) FROM u WHERE u.k = p.tid {{|HAVING COUNT(*) > 5}})",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE NOT EXISTS (SELECT 1 FROM u WHERE u.k = p.tid)",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE t.x IN (SELECT w FROM u) AND p.n IN (SELECT w FROM u)",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n NOT IN (SELECT w FROM u)",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n {{>|=|<>}} (SELECT MAX(w) FROM u)",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON {ON2} WHERE (p.n, t.x) IN ((1, 2), (3, 4))",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n {{>|=|<>}} ALL (SELECT w FROM u)",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n {{>|=|<>}} ANY (SELECT w FROM u)",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n IN UNNEST([1, 2, 3])",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n NOT IN UNNEST([1, 2, 3])",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE CONCAT(t.s, CAST(p.n AS STRING)) = 'a1'",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE t.s || CAST(p.n AS STRING) = 'a1'",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE SAFE_CAST(p.n AS INT64) = 1",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE ABS(p.n) = 1",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.n / t.x > 1",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE {{p.n = p.n|p.n <= p.n|p.n IS NOT NULL OR FALSE|NOT (p.n IS NULL)}}",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} WHERE p.tid = t.id OR p.id = t.id",
    # RIGHT / FULL under WHERE
    f"SELECT t.id, p.n FROM t {SIDE} p ON {ON2} WHERE {PRED}",
    f"SELECT t.id, p.id AS pid FROM t {SIDE} p ON {ON2} WHERE {{t.id IS NULL|p.id IS NULL|t.x > 0|t.x IS NULL OR p.n > 0|COALESCE(t.x, p.n) > 0|t.id = p.tid}}",
    f"SELECT t.id, p.id AS pid, u.v FROM t {SIDE} p ON {ON2} {SIDE} u ON {{u.k = p.tid|u.k = t.id|u.k = COALESCE(p.tid, t.id)|u.k IS NULL}} WHERE {{u.v IS NULL|p.id IS NULL|t.id IS NULL|u.w > 0|TRUE}}",
    f"SELECT t.id, p.id AS pid, u.v FROM t {SIDE} p ON {ON2} {SIDE} u ON {{u.k = p.tid|u.k = t.id|u.k = COALESCE(p.tid, t.id)|u.k IS NULL}}",
    # outer_on_rejection: ON clauses of a later join that reject the padded side of an earlier LEFT join
    f"SELECT t.id, p.n, u.v FROM t LEFT JOIN p ON {ON2} {LR} u ON {{p.n > 10|p.n IS NOT NULL|p.n IS NULL|p.n > 0 OR t.x > 0|p.n > 0 AND u.w = 1|COALESCE(p.n, 0) > 0|u.k = p.tid|u.k = t.id|p.n = u.w OR u.k = 1|p.n > 0 OR u.k = 1|NOT (p.n > 0)}}",
    f"SELECT t.id, p.n, u.v FROM t LEFT JOIN p ON {ON2} {{LEFT JOIN|JOIN}} u ON {{p.n > 10|p.n IS NULL|u.k = p.tid}} {LR} t AS t2 ON {{p.n > 10|p.n IS NULL OR t2.x = 1|u.w = t2.x|p.n = t2.x}}",
    f"SELECT t.id, q.v, u.v AS uv FROM t {{LEFT JOIN|JOIN}} (SELECT p.tid, p.n AS v FROM t AS t0 LEFT JOIN p ON p.tid = t0.id) AS q ON q.tid = t.id {LR} u ON {{q.v > 1|q.v IS NULL|q.v IS NOT NULL|q.v > 1 OR u.k = 1|u.k = q.tid|COALESCE(q.v, 0) > 1}}",
    f"SELECT u.k, q.v FROM u LEFT JOIN (SELECT t0.id, p.n AS v FROM t AS t0 LEFT JOIN p ON p.tid = t0.id) AS q ON {{q.v > 1|q.v IS NULL|q.v IS NOT NULL|q.v > 1 OR u.k = 1|q.id = u.k|q.id = u.k AND q.v > 0|q.id = u.k AND q.v IS NULL|COALESCE(q.v, 0) > 1}}",
    f"SELECT u.k, q.v FROM (SELECT t0.id, p.n AS v FROM t AS t0 LEFT JOIN p ON p.tid = t0.id) AS q {LR} u ON {{q.v > 1|q.v IS NULL|q.v IS NOT NULL|q.id = u.k|q.id = u.k AND q.v > 0|q.id = u.k OR q.v > 0}}",
    # outer_filters: filter above a derived outer join
    f"SELECT d.a, d.c FROM (SELECT t.id AS a, p.n AS c FROM t {SIDE} p ON {ON2} {{|WHERE t.x > 0|WHERE p.b IS NULL|WHERE p.n IS NULL OR t.x > 0}}) AS d WHERE {{d.c IS NOT NULL|d.c > 0|d.a IS NOT NULL|d.a > 0|d.c = d.a|d.c IS NULL|d.c > 0 OR d.a > 0|d.c <> d.a|d.a = 1 AND d.c IS NOT NULL|NOT (d.c IS NULL)|d.c LIKE '%1'}}",
    f"SELECT d.a, d.c FROM (SELECT t.id AS a, p.id AS c FROM t {SIDE} p ON {ON2}) AS d {{LEFT JOIN|RIGHT JOIN|FULL JOIN|JOIN}} u ON {{u.k = d.a|u.k = d.c|d.c IS NULL}} WHERE {{d.c IS NOT NULL|d.c > 0|d.a > 0|u.k > 0|d.c IS NULL}}",
    f"SELECT d.a, d.c FROM (SELECT t.id AS a, p.id AS c FROM t FULL JOIN p ON {ON2}) AS d WHERE d.a {{IS NOT NULL|> 0|IS NULL}} {{AND d.c IS NOT NULL|AND d.c IS NULL|OR d.c IS NULL|}}",
    # outer_join_flatten: computed columns, derived tables and nesting
    f"SELECT d.v, u.v AS uv FROM (SELECT {{COALESCE(p.n, 0)|p.n + 1|p.n IS NULL|t.x|CASE WHEN p.n > 0 THEN 1 ELSE 0 END|IFNULL(p.n, t.x)|NULL|1|CAST(p.n AS INT64)|NOT p.b|p.b OR t.x > 0}} AS v, t.id AS i FROM t LEFT JOIN p ON {ON2}) AS d {SIDE} u ON {{u.k = d.i|u.k = d.v|u.w = d.v|d.v IS NULL|d.v > 0|d.v IS NULL AND u.k = 1}} {{|WHERE d.v > 0|WHERE d.v IS NULL|WHERE u.k IS NULL|WHERE d.v IS NOT NULL|WHERE COALESCE(d.v, 0) > 0}}",
    f"SELECT d.v, COUNT(*) AS c FROM (SELECT {{COALESCE(p.n, 0)|p.n|t.x|p.n IS NULL}} AS v FROM t LEFT JOIN p ON {ON2} {{|WHERE t.x > 0|WHERE p.n IS NULL}}) AS d {{|LEFT JOIN u ON u.k = d.v|RIGHT JOIN u ON u.k = d.v|FULL JOIN u ON u.k = d.v|JOIN u ON u.k = d.v}} GROUP BY d.v",
    f"SELECT SUM(d.v) AS s, COUNT(d.v) AS c, COUNT(*) AS n FROM (SELECT {{COALESCE(p.n, 0)|p.n|t.x}} AS v FROM t LEFT JOIN p ON {ON2}) AS d {{|LEFT JOIN u ON u.k = d.v|RIGHT JOIN u ON u.k = d.v|FULL JOIN u ON u.k = d.v|JOIN u ON u.k = d.v}}",
    f"SELECT d.i FROM (SELECT t.id AS i, p.n AS v FROM t {SIDE} p ON {ON2}) AS d WHERE d.v IS NULL",
    f"SELECT d.i FROM (SELECT t.id AS i, p.n AS v FROM t LEFT JOIN p ON {ON2} WHERE {PRED}) AS d {SIDE} u ON u.k = d.i",
    f"SELECT d.i FROM (SELECT t.id AS i, p.n AS v FROM t LEFT JOIN p ON {ON2} WHERE {PRED}) AS d WHERE d.i > 0",
    f"SELECT a.id, b.v FROM (SELECT t.id, p.n AS v FROM t LEFT JOIN p ON {ON2}) AS a {SIDE} (SELECT t.id, p.n AS v FROM t LEFT JOIN p ON {ON2}) AS b ON a.id = b.id",
    f"SELECT t.id, q.k FROM t {{LEFT JOIN|JOIN}} (u {{LEFT JOIN|JOIN|CROSS JOIN}} p {{ON u.k = p.tid|ON TRUE|ON p.n IS NULL}}) AS q ON {{q.x = t.id|TRUE}}",
    f"SELECT t.id, p.n, u.k FROM t {{LEFT JOIN|JOIN}} (p {{LEFT JOIN|JOIN}} u {{ON u.k = p.tid|ON TRUE|ON u.w IS NULL}}) ON {{p.tid = t.id|p.tid = t.id AND u.k IS NULL|p.tid = t.id AND u.w > 0}} {{|WHERE u.k IS NULL|WHERE u.k IS NOT NULL|WHERE p.n > 0}}",
    f"SELECT t.id, p.n, u.k FROM (t {{LEFT JOIN|JOIN}} p ON p.tid = t.id) {{LEFT JOIN|RIGHT JOIN|JOIN}} u ON {{u.k = p.tid|u.k = t.id|u.k = t.id AND p.n IS NULL}}",
    f"SELECT t.id, p.n, u.k FROM t {{LEFT JOIN|RIGHT JOIN}} (p {{LEFT JOIN|JOIN}} u ON {{u.k = p.tid|u.w IS NULL}}) ON {{p.tid = t.id|p.tid = t.id AND u.k IS NULL|t.x > 0}}",
    f"SELECT a.id, b.id AS bid, c.id AS cid FROM t AS a {SIDE} t AS b ON {{a.id = b.id|a.x = b.y|a.id = b.id AND a.x > 0|a.id = b.id OR b.id IS NULL}} {SIDE} t AS c ON {{c.id = a.id|c.id = b.id|c.id = b.id AND a.x IS NULL|c.id IS NULL}} {{|WHERE a.id IS NULL|WHERE b.id IS NULL|WHERE c.id IS NULL|WHERE b.id IS NOT NULL|WHERE c.x > 0|WHERE a.x IS NULL AND b.x IS NULL}}",
    f"SELECT t.id FROM (SELECT * FROM t WHERE id = {{1|2|10}}) AS t {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} p ON {{t.id = p.tid|t.id = p.tid OR p.tid IS NULL|t.id = p.id|t.x = p.tid}}",
    f"SELECT a.id, p.n FROM (SELECT id, x FROM t WHERE id = {{1|2}}) AS a {{LEFT JOIN|RIGHT JOIN}} p ON {{a.id = p.tid|a.id = p.id AND p.n > 0}} {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} u ON {{a.id = u.k|u.k = p.tid|a.id = u.k OR a.id IS NULL}}",
    f"SELECT a.id, p.n FROM p {{RIGHT JOIN|LEFT JOIN|FULL JOIN}} (SELECT id, x FROM t WHERE id = {{1|2}}) AS a ON a.id = p.tid {{LEFT JOIN|RIGHT JOIN}} u ON a.id = u.k",
    f"SELECT t.id, p.n FROM {{(SELECT * FROM t WHERE FALSE)|(SELECT * FROM t LIMIT 0)|t}} AS t {{FULL JOIN|LEFT JOIN|RIGHT JOIN}} {{(SELECT * FROM p WHERE FALSE)|(SELECT * FROM p WHERE 1 = 0)|p}} AS p ON {ON2}",
    f"SELECT t.id, p.n FROM t FULL JOIN p ON {{FALSE|NULL|1 = 0}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON {{FALSE|NULL|1 = 0}} {{|WHERE p.n IS NULL}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON t.id = p.tid AND p.id = {{1|2|NULL}}",
    # USING / NATURAL
    f"SELECT {{t.id|id|p.id|COALESCE(t.id, p.id)}} AS i, p.n FROM t {SIDE} p USING (id) {{|WHERE p.n > 0|WHERE t.x IS NULL|WHERE p.id IS NULL|WHERE id > 0}}",
    f"SELECT {{id|t.id|u.k}} AS i FROM t {SIDE} p USING (id) {SIDE} u ON u.k = {{p.id|t.id|id}}",
    f"SELECT * FROM t {SIDE} p USING (id)",
    f"SELECT t.*, p.n FROM t {SIDE} p ON {ON2}",
    f"SELECT * FROM t NATURAL {{LEFT JOIN|JOIN|FULL JOIN}} p",
    f"SELECT COUNT(*) AS c, COUNT(id) AS d FROM t {SIDE} p USING (id)",
    f"SELECT id, COUNT(*) AS c FROM t {SIDE} p USING (id) GROUP BY id",
    # grouped outer joins: duplicate-free inputs and anti-join tests
    f"SELECT a.x, b.y FROM (SELECT x FROM t GROUP BY x) AS a {LR} (SELECT y FROM t GROUP BY y) AS b ON {{a.x = b.y|a.x IS NULL OR b.y IS NULL|a.x > b.y|TRUE|a.x = b.y OR b.y IS NULL|a.x IS NOT DISTINCT FROM b.y|b.y IS NULL}}",
    f"SELECT a.x, b.y FROM (SELECT DISTINCT x FROM t) AS a {LR} (SELECT DISTINCT y FROM t) AS b ON {{a.x = b.y|TRUE|b.y IS NULL}} {{|WHERE a.x > 0|WHERE b.y IS NULL}}",
    f"SELECT a.x, b.y FROM (SELECT x FROM t GROUP BY x) AS a {LR} (SELECT y, x FROM t GROUP BY y, x) AS b ON a.x = b.x",
    f"SELECT a.x, b.y, b.z FROM (SELECT x FROM t GROUP BY x) AS a {LR} (SELECT y, x AS z FROM t GROUP BY y, x) AS b ON a.x = b.z",
    f"SELECT a.x, b.y FROM (SELECT x FROM t GROUP BY x, y) AS a {LR} (SELECT y FROM t GROUP BY y) AS b ON a.x = b.y",
    f"SELECT a.x FROM (SELECT x FROM t GROUP BY x) AS a {LR} (SELECT y FROM t GROUP BY y) AS b ON a.x = b.y",
    f"SELECT a.x, b.y FROM (SELECT x FROM t GROUP BY x) AS a LEFT JOIN (SELECT y FROM t GROUP BY y) AS b ON a.x = b.y WHERE {{b.y IS NULL|b.y IS NOT NULL|a.x > 0}}",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON {{o.id = p.tid|o.id = p.tid AND o.x > 0|o.x = p.n|o.id = p.tid OR o.id IS NULL|o.id IS NULL|o.x = 1}} WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE {{s.id = p.tid|s.id = p.tid AND s.x > 0|s.x = p.n|s.id = p.tid OR s.id IS NULL|s.id IS NULL|s.x = 1|s.id = p.tid AND s.x > 1}})",
    f"SELECT {{p.id|o.id|o.x IS NULL|COUNT(*)|COUNT(o.id)|COALESCE(o.x, -1)|p.tid, COUNT(o.x)}} FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid) {{|AND p.n > 0|AND o.id IS NULL|AND o.id IS NOT NULL|AND p.n IS NULL}}",
    f"SELECT p.tid, o.x, COUNT(*) AS c FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid) GROUP BY {{p.tid, o.x|o.x|p.tid|1, 2|p.tid, o.x + 1}}",
    f"SELECT p.id, o.x FROM t AS o RIGHT JOIN p ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS o2 WHERE o2.id = p.tid)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS o WHERE o.id = p.tid) {{|AND p.n > 0}}",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS p WHERE p.id = o.id)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = o.id)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid LIMIT 0)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid) OR p.n > 0",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT (NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid))",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid AND o.x = p.n WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.x = p.n AND s.id = p.tid)",
    f"SELECT p.id FROM p LEFT JOIN t AS o ON o.id = p.tid WHERE NOT EXISTS (SELECT 1 FROM t AS s WHERE s.id = p.tid) AND o.id IS NULL",
    # join_rewrites: FK, HAVING, nested groups, equalities through the join
    f"SELECT p.id, t.x FROM p {{LEFT JOIN|JOIN}} t ON {{p.tid = t.id|p.tid = t.id AND t.x > 0|p.tid = t.id AND p.n > 0|t.id = p.tid}} {{|WHERE t.x IS NULL|WHERE t.x > 0}}",
    f"SELECT p.id, t.x, u.v FROM p LEFT JOIN t ON p.tid = t.id LEFT JOIN u ON u.k = t.y",
    f"SELECT p.id, t.x, u.v FROM p LEFT JOIN u ON u.k = p.tid LEFT JOIN t ON p.tid = t.id",
    f"SELECT a.id, b.id AS bid FROM p AS a {{LEFT JOIN|RIGHT JOIN|FULL JOIN}} p AS c ON a.id = c.id LEFT JOIN t AS b ON a.tid = b.id",
    f"SELECT p.id, t.x FROM t RIGHT JOIN p ON p.tid = t.id",
    f"SELECT t.x, {{COUNT(*)|COUNT(p.id)|SUM(p.n)|MAX(p.n)|MIN(t.y + p.n)|COUNT(DISTINCT p.id)|SUM(t.y)|COUNT(p.n + 1)|AVG(p.n)|COUNT(p.id) + COUNT(*)|SUM(p.n) + SUM(t.y)|COUNT(COALESCE(p.n, 0))|ANY_VALUE(p.n)|ARRAY_LENGTH(ARRAY_AGG(p.n))|SUM(DISTINCT p.n)|COUNTIF(p.n > 0)|LOGICAL_OR(p.b)|MAX(p.n) - MIN(p.n)}} AS a FROM t LEFT JOIN p ON {ON2} GROUP BY t.x HAVING {{COUNT(p.id) > 0|COUNT(p.id) >= 0|COUNT(p.id) = 0|COUNT(p.id) < 1|SUM(p.n) > 1|MAX(p.n) IS NOT NULL|MAX(p.n) IS NULL|COUNT(p.id) > 0 OR t.x = 1|NOT (COUNT(p.id) = 0)|NOT (COUNT(p.id) > 0)|COUNT(p.id) > 0 AND SUM(p.n) > 1|COUNT(DISTINCT p.n) > 0|SUM(p.n) IS NULL OR COUNT(p.id) > 0|COUNT(p.id) <> 0|COUNT(p.id) != 1|MAX(p.n) > 0 OR COUNT(*) > 0|COUNT(p.id) > 0 OR COUNT(p.id) = 0|SUM(p.n) > 1 OR SUM(p.n) <= 1|0 < COUNT(p.id)|COALESCE(SUM(p.n), 0) >= 0}}",
    f"SELECT {{COUNT(p.id)|SUM(p.n)|MAX(p.n)|COUNT(*)}} AS a FROM t LEFT JOIN p ON {ON2} HAVING {{COUNT(p.id) > 0|COUNT(p.id) = 0|SUM(p.n) > 1|SUM(p.n) IS NULL}}",
    f"SELECT t.x, COUNT(p.id) AS a FROM t LEFT JOIN p ON {ON2} GROUP BY {{ROLLUP(t.x)|CUBE(t.x)|GROUPING SETS ((t.x), ())|GROUPING SETS ((), (t.y))}} HAVING COUNT(p.id) > 0",
    f"SELECT p.n, COUNT(p.id) AS a FROM t LEFT JOIN p ON {ON2} GROUP BY p.n HAVING COUNT(p.id) > 0",
    f"SELECT p.n, COUNT(*) AS a FROM t LEFT JOIN p ON {ON2} GROUP BY p.n HAVING COUNT(p.n) > 0",
    f"SELECT t.x, COUNT(p.id) AS a, COUNT(u.k) AS b FROM t LEFT JOIN p ON {ON2} LEFT JOIN u ON u.k = {{p.tid|t.y}} GROUP BY t.x HAVING {{COUNT(p.id) > 0|COUNT(u.k) > 0|COUNT(p.id) > 0 AND COUNT(u.k) > 0|COUNT(p.id) > 0 OR COUNT(u.k) > 0}}",
    f"SELECT t.x, COUNT(p.id) AS a FROM t LEFT JOIN p ON {ON2} GROUP BY t.x HAVING COUNT(p.id) > 0 {{|ORDER BY t.x LIMIT 1}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.tid = t.id WHERE t.id {{= 2|> 1|BETWEEN 1 AND 3|IN (1, 2)|<> 2|IS NULL|IS NOT NULL|NOT IN (1, 2)|NOT BETWEEN 1 AND 3|IN (1, NULL)|= 2 OR t.id = 3|= 2 OR t.id IS NULL|> p.n}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.tid = t.x WHERE t.x {{= 2|> 1|BETWEEN 1 AND 3|IN (1, 2)|<> 2|IS NULL|NOT IN (1, 2)|IN (1, NULL)}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.tid = t.id AND p.n > 1 WHERE t.id {{= 2|> 1|IN (1, 2)}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.tid = t.id OR p.tid IS NULL WHERE t.id {{= 2|> 1|IN (1, 2)}}",
    f"SELECT t.id, p.n, u.v FROM t LEFT JOIN p ON p.tid = t.id LEFT JOIN u ON u.k = p.tid WHERE {{t.id = 2|p.tid = 2|p.tid IN (1, 2)|p.tid IS NULL|p.tid <> 2}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.tid = t.f WHERE t.f {{= 2|> 1.5|= 2.5}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.n = t.f WHERE t.f {{= 2|> 1.5|= 2.5}}",
    f"SELECT t.id, p.n FROM t LEFT JOIN p ON p.n = t.x WHERE t.x {{= 2|> 1.5|= 2.5}}",
    f"SELECT t.id, u.v FROM t LEFT JOIN u ON u.v = t.s WHERE t.s {{= 'a'|= 'A'|> 'a'}}",
    f"SELECT t.id, u.v FROM t LEFT JOIN u ON u.v = CAST(t.x AS STRING) WHERE t.x {{= 1|= 2}}",
    # dedup_join_rules: unread outer-joined sides under duplicate-blind selects
    f"SELECT DISTINCT t.id FROM t {SIDE} p ON {ON2} {{|WHERE t.x > 0|WHERE p.n > 0|WHERE t.id IS NOT NULL}}",
    f"SELECT DISTINCT t.id, t.x FROM t {LR} p ON {ON2}",
    f"SELECT t.x, {{MAX|MIN}}(t.y) AS m FROM t {SIDE} p ON {ON2} GROUP BY t.x",
    f"SELECT t.x, {{COUNT(DISTINCT t.y)|SUM(DISTINCT t.y)|COUNT(t.y)|SUM(t.y)|AVG(t.y)|ANY_VALUE(t.y)|AVG(DISTINCT t.y)}} AS m FROM t {SIDE} p ON {ON2} GROUP BY t.x",
    f"SELECT DISTINCT COUNT(*) AS c FROM t {SIDE} p ON {ON2} GROUP BY t.x",
    f"SELECT DISTINCT t.id, COUNT(*) OVER () AS c FROM t {SIDE} p ON {ON2}",
    f"SELECT DISTINCT t.id, ROW_NUMBER() OVER (ORDER BY t.id) AS r FROM t {SIDE} p ON {ON2}",
    f"SELECT DISTINCT t.id FROM t {SIDE} p ON {ON2} {{|LIMIT 2|ORDER BY t.id LIMIT 1}}",
    f"SELECT DISTINCT t.id FROM t {SIDE} p ON {ON2} WHERE EXISTS (SELECT 1 FROM u WHERE u.k = p.tid)",
    f"SELECT DISTINCT t.id, (SELECT COUNT(*) FROM u WHERE u.k = p.tid) AS c FROM t {SIDE} p ON {ON2}",
    f"SELECT DISTINCT t.id FROM t {SIDE} p ON {ON2} GROUP BY t.id HAVING COUNT(*) {{> 1|> 0}}",
    f"SELECT t.id FROM t {SIDE} p ON {ON2} GROUP BY t.id {{|HAVING MAX(p.n) > 0|HAVING COUNT(*) > 1|HAVING MAX(t.x) > 0}}",
    f"SELECT d.id FROM (SELECT t.id FROM t {SIDE} p ON {ON2}) AS d GROUP BY d.id",
    f"SELECT DISTINCT d.id FROM (SELECT t.id FROM t {SIDE} p ON {ON2} {{|WHERE t.x > 0|WHERE p.n > 0}}) AS d",
    f"SELECT DISTINCT d.id, COUNT(*) OVER () AS c FROM (SELECT t.id FROM t {SIDE} p ON {ON2}) AS d",
    f"SELECT DISTINCT d.id FROM (SELECT t.id FROM t {SIDE} p ON {ON2}) AS d {SIDE} u ON u.k = d.id",
    f"SELECT DISTINCT d.id FROM (SELECT t.id FROM t {SIDE} p ON {ON2} LIMIT 3) AS d",
    f"SELECT DISTINCT d.id, d.n FROM (SELECT t.id, p.n FROM t {SIDE} p ON {ON2}) AS d",
    f"SELECT DISTINCT t.id FROM (SELECT x AS id FROM t GROUP BY x) AS t {SIDE} p ON {ON2}",
    f"SELECT DISTINCT a.id, COUNT(*) AS c FROM (SELECT x AS id FROM t GROUP BY x) AS a {SIDE} (SELECT DISTINCT tid FROM p) AS b ON a.id = b.tid GROUP BY a.id",
    f"SELECT a.id, {{SUM|MAX|MIN|COUNT}}(a.id) AS c FROM (SELECT DISTINCT x AS id FROM t) AS a {SIDE} p ON a.id = p.tid GROUP BY a.id",
    f"SELECT {{COUNT(DISTINCT a.id)|COUNT(*)|SUM(a.id)|MAX(a.id)|COUNT(a.id)}} AS c FROM (SELECT x AS id FROM t GROUP BY x) AS a {SIDE} p ON a.id = p.tid",
    # decorrelated aggregates and domain joins (domain_join_rules)
    f"SELECT t.id, q.c FROM t {{LEFT JOIN|JOIN}} (SELECT p.tid, {{COUNT(*)|COUNT(p.n)|MIN(p.n)|MAX(p.n)|SUM(p.n)|1|TRUE|COUNT(DISTINCT p.n)|AVG(p.n)}} AS c FROM p GROUP BY p.tid) AS q ON q.tid = t.id {{|WHERE q.c IS NULL|WHERE q.c > 0|WHERE COALESCE(q.c, 0) = 0|AND q.c > 0|AND q.c IS NULL}}",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p {{WHERE p.n > 0|WHERE p.tid IS NOT NULL|WHERE p.tid IS NULL|}} GROUP BY p.tid {{|HAVING COUNT(*) > 1}}) AS q ON q.tid = t.{{id|x|y}}",
    f"SELECT t.id, q.c, q.m FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c, MAX(p.n) AS m FROM p GROUP BY p.tid) AS q ON q.tid = t.id {{|AND q.c > 1}}",
    f"SELECT t.id, CASE WHEN q.c IS NULL THEN -1 ELSE q.c END AS c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS q ON q.tid = t.id",
    f"SELECT t.id, q.c FROM t {{LEFT JOIN|JOIN}} (SELECT x.tid, x.c + 1 AS c FROM (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS x) AS q ON q.tid = t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid, p.b) AS q ON q.tid = t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY ROLLUP(p.tid)) AS q ON q.tid = t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS q ON q.tid = t.id AND t.x > 0",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS q ON q.tid IS NOT DISTINCT FROM t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT d.id, g.c FROM (SELECT id FROM t GROUP BY id) AS d LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS g ON d.id {{=|IS NOT DISTINCT FROM}} g.tid) AS q ON q.id = t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT d.x, g.c FROM (SELECT x FROM t GROUP BY x) AS d LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS g ON d.x = g.tid) AS q ON q.x = t.x",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT d.id, g.c FROM (SELECT id FROM t WHERE x > 0 GROUP BY id) AS d LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS g ON d.id = g.tid) AS q ON q.id = t.id",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT d.id, COALESCE(g.c, 0) AS c FROM (SELECT id FROM t GROUP BY id) AS d LEFT JOIN (SELECT p.tid, COUNT(*) AS c FROM p GROUP BY p.tid) AS g ON d.id = g.tid) AS q ON q.id = t.id",
    f"SELECT t.id, q.c FROM t JOIN (SELECT d.id, g.c FROM (SELECT id FROM t GROUP BY id) AS d LEFT JOIN (SELECT p.tid, MAX(p.n) AS c FROM p GROUP BY p.tid) AS g ON d.id = g.tid) AS q ON q.id = t.id AND {{q.c > 0|q.c IS NULL|TRUE}}",
    f"SELECT t.id, q.c FROM t LEFT JOIN (SELECT d.id, g.c FROM (SELECT id FROM t GROUP BY id) AS d LEFT JOIN (SELECT p.tid, MAX(p.n) AS c FROM p GROUP BY p.tid) AS g ON d.id = g.tid) AS q ON q.id = t.id AND q.c > 0",
    # outer joins under UNNEST, lateral, subqueries, set operations
    f"SELECT t.id, g FROM t LEFT JOIN UNNEST({{[1, 2]|[t.x, t.y]|[]|GENERATE_ARRAY(1, t.x)}}) AS g ON {{g = t.x|TRUE|g IS NULL|g > 1}} {{|WHERE g IS NULL|WHERE g > 0}}",
    f"SELECT t.id, g FROM t {{LEFT JOIN|JOIN|CROSS JOIN}} UNNEST({{[1, 2]|[t.x, t.y]|[]}}) AS g",
    f"SELECT t.id, g, p.n FROM t LEFT JOIN UNNEST([1, 2]) AS g ON g = t.x LEFT JOIN p ON p.tid = g",
    f"SELECT t.id, (SELECT COUNT(*) FROM u LEFT JOIN p ON p.tid = u.k WHERE u.k = t.id {{|AND p.n IS NULL|AND p.n > 0}}) AS c FROM t",
    f"SELECT t.id FROM t WHERE EXISTS (SELECT 1 FROM u LEFT JOIN p ON p.tid = u.k WHERE {{u.k = t.id|p.tid = t.id|u.k = t.id AND p.n IS NULL|p.n = t.x}})",
    f"SELECT t.id FROM t WHERE t.x IN (SELECT {{p.n|u.w|p.tid}} FROM u {SIDE} p ON p.tid = u.k)",
    f"SELECT t.id FROM t WHERE t.x NOT IN (SELECT {{p.n|u.w|p.tid}} FROM u {SIDE} p ON p.tid = u.k)",
    f"SELECT t.id, (SELECT MAX(p.n) FROM u RIGHT JOIN p ON p.tid = u.k WHERE p.tid = t.id) AS m FROM t",
    f"SELECT x.id FROM (SELECT t.id FROM t {SIDE} p ON {ON2} UNION ALL SELECT u.k FROM u) AS x",
    f"SELECT t.id FROM t {SIDE} p ON {ON2} {{UNION ALL|UNION DISTINCT|INTERSECT DISTINCT|EXCEPT DISTINCT}} SELECT p.tid FROM p",
    f"SELECT t.id FROM t LEFT JOIN p ON {ON2} EXCEPT DISTINCT SELECT t.id FROM t JOIN p ON {ON2}",
    f"WITH q AS (SELECT t.id, p.n FROM t {SIDE} p ON {ON2}) SELECT q.id FROM q WHERE q.n {{> 0|IS NULL|IS NOT NULL}}",
    f"WITH q AS (SELECT t.id, p.n FROM t LEFT JOIN p ON {ON2}) SELECT q1.id, q2.n FROM q AS q1 {SIDE} q AS q2 ON q1.id = q2.id",
    f"WITH t AS (SELECT * FROM t WHERE x > 0) SELECT t.id, p.n FROM t {SIDE} p ON p.tid = t.id",
    f"SELECT t.id, p.n FROM t {SIDE} p ON p.tid = t.id QUALIFY ROW_NUMBER() OVER (PARTITION BY t.id ORDER BY p.n) = 1",
    f"SELECT t.id, SUM(p.n) OVER (PARTITION BY t.id) AS s FROM t {SIDE} p ON {ON2} WHERE {PRED}",
    f"SELECT t.id, ROW_NUMBER() OVER (ORDER BY t.id, p.id) AS r FROM t {SIDE} p ON {ON2} WHERE {PRED}",
    f"SELECT t.id, p.n FROM t {SIDE} p ON {ON2} WHERE {PRED} ORDER BY t.id, p.n LIMIT {{1|2|100}}",
    f"SELECT t.x, COUNT(*) AS c, COUNT(p.id) AS d, SUM(p.n) AS s FROM t {SIDE} p ON {ON2} WHERE {PRED} GROUP BY ROLLUP(t.x)",
    f"SELECT p.tid, COUNT(*) AS c FROM p {SIDE} t ON {ON2} WHERE {PRED} GROUP BY p.tid",
    f"SELECT COALESCE(t.id, p.tid) AS k, COUNT(*) AS c, COUNT(t.id) AS a, COUNT(p.id) AS b FROM t FULL JOIN p ON p.tid = t.id GROUP BY k",
    f"SELECT COALESCE(t.id, p.tid) AS k, COUNT(*) AS c FROM t FULL JOIN p ON p.tid = t.id WHERE {{t.id IS NULL|p.id IS NULL|t.id IS NOT NULL|p.id IS NOT NULL|t.x > 0|p.n > 0|t.x > 0 OR p.n > 0|t.id = p.tid}} GROUP BY k",
    f"SELECT COUNT(*) AS c FROM t FULL JOIN p ON p.tid = t.id WHERE {{t.id IS NULL OR p.id IS NULL|t.id IS NULL AND p.id IS NULL|t.id IS NULL|p.id IS NULL|t.id IS NOT NULL AND p.id IS NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE p.tid IS NULL {{|AND p.id IS NULL|AND t.x > 0|AND p.n IS NULL}}",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id AND p.n > 0 WHERE {{p.id IS NULL|p.tid IS NULL|p.n IS NULL|p.b IS NULL}}",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id WHERE p.id IS NULL AND NOT EXISTS (SELECT 1 FROM u WHERE u.k = t.id)",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id LEFT JOIN u ON u.k = t.id WHERE p.id IS NULL AND u.k IS NULL",
    f"SELECT t.id FROM t LEFT JOIN p ON p.tid = t.id LEFT JOIN u ON u.k = {{p.tid|p.id}} WHERE u.k IS NULL",
    f"SELECT t.id FROM t LEFT JOIN (SELECT DISTINCT tid FROM p) AS q ON q.tid = t.id WHERE q.tid IS NULL",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid, {{TRUE|COUNT(*)|1}} AS f FROM p GROUP BY tid) AS q ON q.tid = t.id WHERE q.f IS {{NULL|NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid, 1 AS f FROM p) AS q ON q.tid = t.id WHERE q.f IS {{NULL|NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN (SELECT DISTINCT tid, 1 AS f FROM p) AS q ON q.tid = t.id WHERE q.f IS {{NULL|NOT NULL}}",
    f"SELECT t.id, COUNT(*) AS c FROM t LEFT JOIN (SELECT DISTINCT tid, 1 AS f FROM p) AS q ON q.tid = t.id WHERE q.f IS NOT NULL GROUP BY t.id",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid FROM p {{|WHERE n > 0}} GROUP BY tid) AS q ON q.tid = t.id WHERE q.tid IS {{NULL|NOT NULL}}",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid FROM p GROUP BY tid) AS q ON q.tid = t.id AND t.x > 0 WHERE q.tid IS NULL",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid FROM p GROUP BY tid) AS q ON q.tid IS NOT DISTINCT FROM t.id WHERE q.tid IS NULL",
    f"SELECT t.id FROM t LEFT JOIN (SELECT tid FROM p GROUP BY tid) AS q ON q.tid = t.id OR t.id IS NULL WHERE q.tid IS NULL",
]

TEMPLATES += MORE


# Templates that need p.tid to be a NOT NULL foreign key to t.id (the schema draws that only now and then, so these
# cases force it): the foreign-key joins, with the child null-extended by an earlier or later outer join and ON
# clauses that say more than the key.
FK_ON = "{p.tid = par.id|p.tid = par.id AND par.x > 0|p.tid = par.x AND p.tid = par.id|p.tid = par.id AND p.tid = par.x|p.tid = par.id AND p.id = par.id|p.tid = par.id AND p.tid = par.id|par.id = p.tid|p.tid = par.id OR par.x = 1}"
FK_TEMPLATES = [
    f"SELECT p.id FROM p {{JOIN|LEFT JOIN}} t AS par ON {FK_ON}",
    f"SELECT p.id, par.x FROM p {{JOIN|LEFT JOIN}} t AS par ON {FK_ON}",
    f"SELECT p.id FROM t AS par {{JOIN|LEFT JOIN}} p ON {FK_ON}",
    f"SELECT a.id FROM t AS a {{LEFT JOIN|JOIN}} p ON p.tid = a.id {{JOIN|LEFT JOIN}} t AS par ON {FK_ON}",
    f"SELECT a.id, par.x FROM t AS a {{LEFT JOIN|JOIN}} p ON p.tid = a.id {{JOIN|LEFT JOIN}} t AS par ON {FK_ON}",
    f"SELECT a.id FROM p {{RIGHT JOIN|FULL JOIN|LEFT JOIN}} t AS a ON p.tid = a.id JOIN t AS par ON {FK_ON}",
    f"SELECT a.id FROM t AS a {{LEFT JOIN|JOIN}} p ON p.tid = a.id JOIN t AS par ON {FK_ON} WHERE {{p.id IS NOT NULL|p.tid IS NOT NULL|a.x > 0|p.id IS NULL}}",
    f"SELECT a.id FROM t AS a LEFT JOIN p ON p.tid = a.id {{RIGHT JOIN|FULL JOIN}} u ON u.k = a.id JOIN t AS par ON {FK_ON}",
    f"SELECT a.id FROM t AS a LEFT JOIN p ON p.tid = a.id JOIN t AS par ON {FK_ON} {{RIGHT JOIN|FULL JOIN|LEFT JOIN}} u ON u.k = a.id",
    f"SELECT p.id, COUNT(*) AS c FROM p {{JOIN|LEFT JOIN}} t AS par ON {FK_ON} GROUP BY p.id",
    f"SELECT par.id, COUNT(p.id) AS c FROM t AS par {{LEFT JOIN|JOIN}} p ON {FK_ON} GROUP BY par.id",
    f"SELECT p.id FROM p {{JOIN|LEFT JOIN}} t AS par ON {FK_ON} {{JOIN|LEFT JOIN}} t AS par2 ON p.tid = par2.id",
    f"SELECT p.id FROM p {{LEFT JOIN|JOIN}} (SELECT id, x FROM t {{|WHERE x > 0}}) AS par ON p.tid = par.id",
    f"SELECT DISTINCT par.id FROM t AS par {{LEFT JOIN|JOIN|RIGHT JOIN}} p ON {FK_ON}",
]


def cases(seed: int, count: int) -> list[dict]:
    general = expand(TEMPLATES, seed, count - count // 5, "outer_joins")
    forced = expand(FK_TEMPLATES, seed + 1, count // 5, "outer_joins_fk")
    for case in forced:
        case["constraints"]["p"]["foreign_keys"] = [[["tid"], "t", ["id"]]]
        case["constraints"]["p"]["not_null"] = sorted(set(case["constraints"]["p"]["not_null"]) | {"tid"})
    return general + forced
