-- ADAPTED, not upstream. BigQuery DDL for the Oracle Customer Orders (CO) sample schema
-- (oracle-samples/db-sample-schemas, customer_orders/co_create.sql at commit
-- 6660bad68c07bd143430ace58565b3f727e17263; the unchanged Oracle scripts are in ../upstream/,
-- licence in ../upstream/LICENSE.txt).
--
-- Adaptation:
-- * Oracle types become BigQuery types: INTEGER -> INT64; NUMBER(p, s) -> NUMERIC(p, s);
--   VARCHAR2(n CHAR) -> STRING; TIMESTAMP -> DATETIME (microseconds: the upstream values have nine
--   fractional digits and are truncated); DATE -> DATE; BLOB -> BYTES, except products.product_details:
--   upstream stores JSON text as bytes (UTL_RAW.CAST_TO_RAW of the JSON) and the column is a STRING here
--   holding the same text, because the DuckDB the eval runs on cannot read BigQuery's CAST(bytes AS STRING)
--   as text (sqlglot translates it to a cast that returns the escaped bytes). The image and logo BLOB
--   columns are NULL in every upstream row.
-- * Primary and foreign keys are declared NOT ENFORCED, as BigQuery declares them.
-- * Dropped, because BigQuery has no such objects: GENERATED BY DEFAULT ON NULL AS IDENTITY, indexes,
--   the UNIQUE constraints (customers.email_address, stores.store_name, order_items (product_id,
--   order_id), inventory (store_id, product_id)), the CHECK constraints (orders.order_status and
--   shipments.shipment_status value lists, a store with at least one address, product_details is
--   json) and comments. The four views are adapted in ../workload.json.
-- Tables, columns, column order, NOT NULL, primary keys and foreign keys are the upstream ones;
-- tools/sample_db_bench.py checks that against the upstream script on every run.

CREATE TABLE customers (
  customer_id INT64 NOT NULL,
  email_address STRING NOT NULL,
  full_name STRING NOT NULL,
  PRIMARY KEY (customer_id) NOT ENFORCED
);

CREATE TABLE inventory (
  inventory_id INT64 NOT NULL,
  store_id INT64 NOT NULL,
  product_id INT64 NOT NULL,
  product_inventory INT64 NOT NULL,
  PRIMARY KEY (inventory_id) NOT ENFORCED,
  FOREIGN KEY (store_id) REFERENCES stores(store_id) NOT ENFORCED,
  FOREIGN KEY (product_id) REFERENCES products(product_id) NOT ENFORCED
);

CREATE TABLE order_items (
  order_id INT64 NOT NULL,
  line_item_id INT64 NOT NULL,
  product_id INT64 NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  quantity INT64 NOT NULL,
  shipment_id INT64,
  PRIMARY KEY (order_id, line_item_id) NOT ENFORCED,
  FOREIGN KEY (order_id) REFERENCES orders(order_id) NOT ENFORCED,
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id) NOT ENFORCED,
  FOREIGN KEY (product_id) REFERENCES products(product_id) NOT ENFORCED
);

CREATE TABLE orders (
  order_id INT64 NOT NULL,
  order_tms DATETIME NOT NULL,
  customer_id INT64 NOT NULL,
  order_status STRING NOT NULL,
  store_id INT64 NOT NULL,
  PRIMARY KEY (order_id) NOT ENFORCED,
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id) NOT ENFORCED,
  FOREIGN KEY (store_id) REFERENCES stores(store_id) NOT ENFORCED
);

CREATE TABLE products (
  product_id INT64 NOT NULL,
  product_name STRING NOT NULL,
  unit_price NUMERIC(10, 2),
  product_details STRING,
  product_image BYTES,
  image_mime_type STRING,
  image_filename STRING,
  image_charset STRING,
  image_last_updated DATE,
  PRIMARY KEY (product_id) NOT ENFORCED
);

CREATE TABLE shipments (
  shipment_id INT64 NOT NULL,
  store_id INT64 NOT NULL,
  customer_id INT64 NOT NULL,
  delivery_address STRING NOT NULL,
  shipment_status STRING NOT NULL,
  PRIMARY KEY (shipment_id) NOT ENFORCED,
  FOREIGN KEY (store_id) REFERENCES stores(store_id) NOT ENFORCED,
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id) NOT ENFORCED
);

CREATE TABLE stores (
  store_id INT64 NOT NULL,
  store_name STRING NOT NULL,
  web_address STRING,
  physical_address STRING,
  latitude NUMERIC(9, 6),
  longitude NUMERIC(9, 6),
  logo BYTES,
  logo_mime_type STRING,
  logo_filename STRING,
  logo_charset STRING,
  logo_last_updated DATE,
  PRIMARY KEY (store_id) NOT ENFORCED
);
