"""Run the R-Bot repository's Calcite rewrite pairs through KumoSQL's provers.

R-Bot (https://github.com/curtis-sun/LLM4Rewrite, Apache-2.0) ships 44 queries
from Apache Calcite's rewrite-rule tests, each with the SQL Calcite's rule
produces (45 pairs). Its TPC-H and DSB folders only hold template instances
(same query, different constants), not rewrites; those are generated by an LLM
at run time, so there are no pairs to score.

For every pair this reports ``proved``, ``different`` (the prover failed and a
random-database search found a counterexample, re-checked by running both
queries in DuckDB; these leave the score's denominator, since they are not equivalent), ``unknown`` and ``wrong`` (proved, yet a counterexample
exists; must stay 0).

    python tools/rbot_bench.py
"""

from __future__ import annotations

import json
from pathlib import Path
import re
import sys
import time

import sqlglot
from sqlglot import exp

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sqlsolver_bench as sb  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "rbot"


_COMPARISONS = (exp.EQ, exp.NEQ, exp.GT, exp.GTE, exp.LT, exp.LTE)


def normalise(sql: str) -> str:
    """Calcite quotes identifiers with double quotes; the shared harness reads MySQL.

    Calcite's ``IS [NOT] TRUE/FALSE/NULL/UNKNOWN`` binds more loosely than a comparison, so its
    ``a > b IS NOT TRUE`` means ``(a > b) IS NOT TRUE``. sqlglot parses the test as the comparison's
    right operand (``a > NOT b IS TRUE``), so the tests are moved back onto the whole comparison and
    the comparison is printed in parentheses, which every reader (sqlglot, DuckDB) takes the same way.
    """

    text = sql.strip().rstrip(";")
    tree = sqlglot.parse_one(text, read="postgres")
    if re.search(r"(=|<|>)\s*NOT\b", text, re.IGNORECASE):
        # ``a > NOT b IS TRUE`` parses to the same tree as ``a > b IS NOT TRUE``; Calcite never prints it.
        raise ValueError("a comparison operand starting with NOT is ambiguous after parsing")
    for node in list(tree.find_all(*_COMPARISONS)):
        layers, operand = [], node.expression
        while True:  # the unparenthesized IS tests sqlglot hung on the right operand, outermost first
            if isinstance(operand, exp.Is):
                layers.append(operand)
                operand = operand.this
            elif isinstance(operand, exp.Not) and isinstance(operand.this, exp.Is):
                layers.append(operand)
                operand = operand.this.this
            else:
                break
        if not layers:
            continue
        # comparison(a, L1(... Ln(b) ...)) becomes L1((... Ln((comparison(a, b))) ...))
        node.replace(layers[0])
        inner = node
        for layer in reversed(layers):
            test = layer.this if isinstance(layer, exp.Not) else layer
            test.set("this", exp.Paren(this=inner))
            inner = layer
        node.set("expression", operand)
    return tree.sql(dialect="mysql")


def load_pairs() -> list[tuple[str, str, str]]:
    pairs = []
    for line in (FIXTURES / "calcite.jsonl").read_text(encoding="utf-8").splitlines():
        row = json.loads(line)
        for rewrite in row["rewrites"]:
            pairs.append((rewrite["name"], row["input_sql"], rewrite["output_sql"]))
    return pairs


def run(prove=sb.default_prove, trials: int = 60) -> dict:
    tables = sb.load_schema(FIXTURES / "create_tables.sql")
    db = sb.new_database(tables)
    out = {"total": 0, "proved": 0, "different": [], "unknown": [], "wrong": [], "seconds": 0.0}
    start = time.time()
    for name, left, right in load_pairs():
        out["total"] += 1
        try:
            left, right = normalise(left), normalise(right)
            proof = prove(left, right, tables, True)
        except Exception:
            proof = False
        counter = sb.differ(left, right, tables, db, trials, constants=True) if _parses(left, right) else False
        if proof:
            if counter not in (None, False):
                out["wrong"].append(name)
            else:
                out["proved"] += 1
        elif counter not in (None, False):
            out["different"].append(name)
        else:
            out["unknown"].append(name)
    out["scored"] = out["total"] - len(out["different"])  # a pair with a replayed counterexample is not one to prove
    out["seconds"] = time.time() - start
    return out


def _parses(*queries: str) -> bool:
    try:
        for query in queries:
            sqlglot.parse_one(query, read="mysql")
    except sqlglot.errors.SqlglotError:
        return False
    return True


def main() -> int:
    r = run()
    print(f"rbot-calcite {r['proved']}/{r['scored']} proved ({r['total']} pairs), {len(r['different'])} different (counterexample), {len(r['unknown'])} unknown, {len(r['wrong'])} wrong, {r['seconds']:.1f}s")
    for key in ("different", "unknown", "wrong"):
        if r[key]:
            print(f"  {key}: {', '.join(r[key])}")
    return 1 if r["wrong"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
