"""Run the R-Bot repository's Calcite rewrite pairs through KumoSQL's provers.

R-Bot (https://github.com/curtis-sun/LLM4Rewrite, Apache-2.0) ships 44 queries
from Apache Calcite's rewrite-rule tests, each with the SQL Calcite's rule
produces (45 pairs). Its TPC-H and DSB folders only hold template instances
(same query, different constants), not rewrites; those are generated by an LLM
at run time, so there are no pairs to score.

For every pair this reports ``proved``, ``different`` (the prover failed and a
random-database search found a counterexample, re-checked by running both
queries in DuckDB), ``unknown`` and ``wrong`` (proved, yet a counterexample
exists; must stay 0).

    python tools/rbot_bench.py
"""

from __future__ import annotations

import json
from pathlib import Path
import sys
import time

import sqlglot

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sqlsolver_bench as sb  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "rbot"


def normalise(sql: str) -> str:
    """Calcite quotes identifiers with double quotes; the shared harness reads MySQL."""

    return sqlglot.transpile(sql.strip().rstrip(";"), read="postgres", write="mysql")[0]


def load_pairs() -> list[tuple[str, str, str]]:
    pairs = []
    for line in (FIXTURES / "calcite.jsonl").read_text(encoding="utf-8").splitlines():
        row = json.loads(line)
        for rewrite in row["rewrites"]:
            pairs.append((rewrite["name"], row["input_sql"], rewrite["output_sql"]))
    return pairs


def run(prove=sb.default_prove, trials: int = 60) -> dict:
    tables = sb.load_schema(FIXTURES / "create_tables.sql")
    db = sb.new_database(tables)
    out = {"total": 0, "proved": 0, "different": [], "unknown": [], "wrong": [], "seconds": 0.0}
    start = time.time()
    for name, left, right in load_pairs():
        out["total"] += 1
        try:
            left, right = normalise(left), normalise(right)
            proof = prove(left, right, tables, True)
        except Exception:
            proof = False
        counter = sb.differ(left, right, tables, db, trials, constants=True) if _parses(left, right) else False
        if proof:
            if counter not in (None, False):
                out["wrong"].append(name)
            else:
                out["proved"] += 1
        elif counter not in (None, False):
            out["different"].append(name)
        else:
            out["unknown"].append(name)
    out["seconds"] = time.time() - start
    return out


def _parses(*queries: str) -> bool:
    try:
        for query in queries:
            sqlglot.parse_one(query, read="mysql")
    except sqlglot.errors.SqlglotError:
        return False
    return True


def main() -> int:
    r = run()
    print(f"rbot-calcite {r['proved']}/{r['total']} proved, {len(r['different'])} different (counterexample), {len(r['unknown'])} unknown, {len(r['wrong'])} wrong, {r['seconds']:.1f}s")
    for key in ("different", "unknown", "wrong"):
        if r[key]:
            print(f"  {key}: {', '.join(r[key])}")
    return 1 if r["wrong"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
