"""Regenerate the README benchmark scoreboard from benchmarks/results/*.json.

    python tools/scoreboard.py          # rewrite the table between the markers
    python tools/scoreboard.py --check  # exit 1 if the README is out of date

Each eval owns one results file (``benchmarks/results/<eval>.json``) with the
keys documented in benchmarks/README.md.
After a change that moves a score, edit that file and rerun this script. On a
README merge conflict, take either side of the table and rerun it.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- scoreboard:begin (generated by tools/scoreboard.py from benchmarks/results/*.json; do not edit by hand) -->"
END = "<!-- scoreboard:end -->"
KEYS = ("suite", "order", "size", "score", "metric", "evidence", "correctness", "coverage", "held_out", "docs", "command", "date", "caveats")
EVIDENCE = {"proof": "Unbounded proof", "bounded": "Bounded verification", "executed": "Executed datasets"}
OUTCOMES = ("proven", "refuted", "unknown", "unsupported", "timeout", "error")
EXTRA = (("usefulness", "Usefulness"), ("analysis", "Analysis quality"), ("performance", "Performance"))


def load() -> list[dict]:
    rows, problems = [], []
    for path in sorted((ROOT / "benchmarks" / "results").glob("*.json")):
        row = json.loads(path.read_text(encoding="utf-8"))
        missing = [k for k in KEYS if k not in row]
        if missing:
            raise SystemExit(f"{path.name}: missing {', '.join(missing)}")
        if row["evidence"] not in EVIDENCE:
            raise SystemExit(f"{path.name}: evidence must be one of {', '.join(EVIDENCE)}")
        problem = check(row)
        if problem:
            problems.append(f"{path.name}: {problem}")
        rows.append(row)
    if problems:
        raise SystemExit("\n".join(problems))
    return sorted(rows, key=lambda r: (r["order"], r["suite"]))


def check(row: dict) -> str | None:
    """What is wrong with a results row's optional keys and coverage counts, or None.

    Nonempty ``coverage`` counts must add up to ``size``. When they count another unit (traced columns, the
    rewrite steps that changed the SQL), a stage (cases skipped before translation as well as the scored ones) or a
    subset (the pairs another row leaves unknown, failures only), the row says so in ``coverage_of``: one sentence
    naming the unit and its total. ``environment``, when present, is an object (library versions, git commit)."""

    coverage = row["coverage"]
    if not isinstance(coverage, dict):
        return "coverage must be an object"
    bad = [k for k in coverage if k not in OUTCOMES]
    if bad:
        return f"unknown coverage outcome {', '.join(bad)}"
    invalid = [v for v in coverage.values() if not (isinstance(v, int) and not isinstance(v, bool) and v >= 0)]
    if invalid:
        return "coverage counts must be whole numbers, 0 or more"
    if "coverage_of" in row and not (isinstance(row["coverage_of"], str) and row["coverage_of"].strip()):
        return "coverage_of must be a sentence naming what coverage counts and its total"
    if coverage and sum(coverage.values()) != row["size"] and "coverage_of" not in row:
        return (
            f"coverage adds up to {sum(coverage.values())}, not size {row['size']}: fix the counts, or say what they count "
            "in coverage_of (see benchmarks/README.md)"
        )
    if "environment" in row and not isinstance(row["environment"], dict):
        return "environment must be an object"
    return None


def cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def link(r: dict) -> str:
    return f"[{cell(r['suite'])}]({r['docs']})"


def table(rows: list[dict]) -> str:
    out = ["**Correctness**", "", "| Eval | Evidence | Size | Score | Correctness | Held-out | As of | Caveats |", "| --- | --- | ---: | --- | --- | --- | --- | --- |"]
    for r in rows:
        out.append(
            f"| {link(r)} | {EVIDENCE[r['evidence']]} | {r['size']} | **{cell(r['score'])}**: {cell(r['metric'])} | {cell(r['correctness'])} | {cell(r['held_out'])} | {r['date']} | {cell(r['caveats'])} |"
        )
    out += ["", "**Coverage** (pairs or cases by outcome)", "", "| Eval | " + " | ".join(o.title() for o in OUTCOMES) + " |", "| --- | " + " | ".join("---:" for _ in OUTCOMES) + " |"]
    for r in rows:
        out.append(f"| {link(r)} | " + " | ".join(str(r["coverage"].get(o, "–")) for o in OUTCOMES) + " |")
    extra = [r for r in rows if any(r.get(k) for k, _ in EXTRA)]
    if extra:
        out += ["", "**Usefulness, analysis quality and performance**", "", "| Eval | " + " | ".join(t for _, t in EXTRA) + " |", "| --- | " + " | ".join("---" for _ in EXTRA) + " |"]
        for r in extra:
            out.append(f"| {link(r)} | " + " | ".join(cell(r.get(k) or "–") for k, _ in EXTRA) + " |")
    return "\n".join(out)


def render(text: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit("README.md has no scoreboard markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{table(load())}\n{END}{tail}"


def main(argv: list[str]) -> int:
    old = README.read_text(encoding="utf-8")
    new = render(old)
    if "--check" in argv:
        if old != new:
            print("README scoreboard is out of date: run python tools/scoreboard.py")
            return 1
        return 0
    if old != new:
        README.write_text(new, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
