"""Regenerate the README benchmark scoreboard from benchmarks/results/*.json.

    python tools/scoreboard.py          # rewrite the table between the markers
    python tools/scoreboard.py --check  # exit 1 if the README is out of date

Each eval owns one results file (``benchmarks/results/<eval>.json``) with the
keys documented in benchmarks/README.md.
After a change that moves a score, edit that file and rerun this script. On a
README merge conflict, take either side of the table and rerun it.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- scoreboard:begin (generated by tools/scoreboard.py from benchmarks/results/*.json; do not edit by hand) -->"
END = "<!-- scoreboard:end -->"
KEYS = ("suite", "order", "size", "score", "metric", "evidence", "correctness", "coverage", "held_out", "docs", "command", "date", "caveats")
EVIDENCE = {"proof": "Unbounded proof", "bounded": "Bounded verification", "executed": "Executed datasets"}
OUTCOMES = ("proven", "refuted", "unknown", "unsupported", "timeout", "error")
EXTRA = (("usefulness", "Usefulness"), ("analysis", "Analysis quality"), ("performance", "Performance"))


def load() -> list[dict]:
    rows = []
    for path in sorted((ROOT / "benchmarks" / "results").glob("*.json")):
        row = json.loads(path.read_text(encoding="utf-8"))
        missing = [k for k in KEYS if k not in row]
        if missing:
            raise SystemExit(f"{path.name}: missing {', '.join(missing)}")
        if row["evidence"] not in EVIDENCE:
            raise SystemExit(f"{path.name}: evidence must be one of {', '.join(EVIDENCE)}")
        bad = [k for k in row["coverage"] if k not in OUTCOMES]
        if bad:
            raise SystemExit(f"{path.name}: unknown coverage outcome {', '.join(bad)}")
        rows.append(row)
    return sorted(rows, key=lambda r: (r["order"], r["suite"]))


def cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def link(r: dict) -> str:
    return f"[{cell(r['suite'])}]({r['docs']})"


def table(rows: list[dict]) -> str:
    out = ["**Correctness**", "", "| Eval | Evidence | Size | Score | Correctness | Held-out | As of | Caveats |", "| --- | --- | ---: | --- | --- | --- | --- | --- |"]
    for r in rows:
        out.append(
            f"| {link(r)} | {EVIDENCE[r['evidence']]} | {r['size']} | **{cell(r['score'])}**: {cell(r['metric'])} | {cell(r['correctness'])} | {cell(r['held_out'])} | {r['date']} | {cell(r['caveats'])} |"
        )
    out += ["", "**Coverage** (pairs or cases by outcome)", "", "| Eval | " + " | ".join(o.title() for o in OUTCOMES) + " |", "| --- | " + " | ".join("---:" for _ in OUTCOMES) + " |"]
    for r in rows:
        out.append(f"| {link(r)} | " + " | ".join(str(r["coverage"].get(o, "–")) for o in OUTCOMES) + " |")
    extra = [r for r in rows if any(r.get(k) for k, _ in EXTRA)]
    if extra:
        out += ["", "**Usefulness, analysis quality and performance**", "", "| Eval | " + " | ".join(t for _, t in EXTRA) + " |", "| --- | " + " | ".join("---" for _ in EXTRA) + " |"]
        for r in extra:
            out.append(f"| {link(r)} | " + " | ".join(cell(r.get(k) or "–") for k, _ in EXTRA) + " |")
    return "\n".join(out)


def render(text: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit("README.md has no scoreboard markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{table(load())}\n{END}{tail}"


def main(argv: list[str]) -> int:
    old = README.read_text(encoding="utf-8")
    new = render(old)
    if "--check" in argv:
        if old != new:
            print("README scoreboard is out of date: run python tools/scoreboard.py")
            return 1
        return 0
    if old != new:
        README.write_text(new, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
